### ISSUE TITLE
Available way to "Manage Secure Certificates"

### ISSUE THREAD

**Issue by huggi** [diafygi/gethttpsforfree#1]
I see that: https://gethttpsforfree.com/ is a brand new thing and I want to outline, that I'm having a different environment, which is currently as the following:

At my ISPs admin-panel, I have the 3 following menu options:

Step 1: Generate CSR

```
entries below have been populated with information associated with your account.
Please check the entries for validity before submitting the form.
```

Input Values:

```
Certificate Details
Common Name: Text
Organization: Text
Department: Text
Email contact: E-Mail address
City: Text
State/Region: Text
Country: Text
Key Size: 1024/2048/4096
```

Step 2: Install Self Signed Certificate

```
Paste your certificate information below then
```

Step 3: Install SSL Certificate

```
Paste your certificate information below then
Certificate Credentials:
Certificate
Private key
CA Chain
```

Error message:

```
Errors occurred during the install

Result: Failure
Flag:    warning

Error:   Certificate/Key mismatch [ C:9cd05409c5884b8d01785b2e1a28fa46 | K:34a5accdf58620444416ab202dc50782 ]
```

I'm trying to get more details from my hoster. I've added in total 4 domains on the white-list and created support requests for them. Basically it should work soon. Thank you very much anyway!

**Comment by diafygi** [comment]
Sorry, specific hosting provider interfaces and certificate management is not within the scope of this project. It is up to each individual website owner to manage their own certificates how they choose.

**Comment by huggi** [comment]
Maybe it's good to know that XYZ does not provide support and ABC is able to do it. Maybe there is a possibility to set-up a list of hosting providers which are able to support it, so people don't have expectations that it works _anywhere_ happy to provide you my details if interested.
