### ISSUE TITLE
Request: SHA512 signatures

### ISSUE THREAD

**Issue by stolendata** [diafygi/gethttpsforfree#10]

**Comment by diafygi** [comment]
RS256 is [recommended](https://tools.ietf.org/html/rfc7518#section-3.1) by the JWS spec. Will move to whatever is recommended when it changes.

**Comment by stolendata** [comment]
2048 bit RSA is also what's generally recommended today, but that doesn't rule out 4096 bit RSA as a sensible option - as used by yourself as the default in your examples for generating keys and Diffie-Hellman params.

I should've mentioned that it would've been nice to have OPTIONS rather than just a single enforced recommended choice. What is the rationale behind that?
