### ISSUE TITLE
Account Public Key

### ISSUE THREAD

**Issue by msrnoob** [diafygi/gethttpsforfree#101]
How can I generate the Account Public Key? 

Sorry I have no idea about this.

**Comment by licaon-kter** [comment]
Press the **(how do I generate this?)** link on the right side of the box there.

**Comment by msrnoob** [comment]
It says:

> Generate an account private key if you don't have one:
> (KEEP ACCOUNT.KEY SECRET!)
> openssl genrsa 4096 > account.key
> Print your public key:
> openssl rsa -in account.key -pubout
> Copy and paste the public key into the box below.

I am not a tech savvy as you. I intend to use the ssl certificate on shared hosting which use cpanel. 

Is there any tutorial which may guide me to generate the account key?

**Comment by omBratteng** [comment]
@imosman Open your terminal and enter `openssl genrsa 4096 > account.key` then enter `openssl rsa -in account.key -pubout`

**Comment by omBratteng** [comment]
@imosman Then you'll get something like this
![Preview](https://i.bratteng.xyz/qLN8oTEyAl.png)

**Comment by licaon-kter** [comment]
I did not answer because @tnViking now you need to explain either how to get MSYS and Openssl on Windows or how to run Lubuntu in Virtualbox and how to extract keys from the VM. :)

**Comment by msrnoob** [comment]
@licaon-kter @tnViking Thanks to both of you. 

Though @licaon-kter  is right, but I will not ask anymore question. hats off to both of you.
