### ISSUE TITLE
Make `CA` configurable.

### ISSUE THREAD

**Issue by ypid** [diafygi/gethttpsforfree#102]
I think it would make sense to make the the `CA` variable configurable by the user so that the staging API can easily by used. What do you think?

Ref: [js/index.js](https://github.com/diafygi/gethttpsforfree/blob/d1b59053d4286e90cc1f98a098df8761c6da0f1a/js/index.js#L6-L7)

**Comment by ypid** [comment]
@leveled-up: Thanks for the feedback. Can you educate me why this is a bad idea?

**Comment by licaon-kter** [comment]
What other CA do you have in mind?

**Comment by leveled-up** [comment]
@ypid I think you should keep it as simple as possible.

**Comment by ypid** [comment]
Didn’t you guys check my ref from above :wink:? I meant something like a drop down menu to make it easy to select https://acme-staging.api.letsencrypt.org/ for testing.

**Comment by licaon-kter** [comment]
I saw that, you can just edit your local copy an be done.

**Comment by ypid** [comment]
@licaon-kter You are right. The thing is that not everybody is comfortable with doing that. I have the typical Windows Admin in mind. So, is there any interest in this feature?

**Comment by licaon-kter** [comment]
You can't have both, you are daring enough to play with testing but you can't edit a text file? C'mon. :)

**Comment by ypid** [comment]
I did not suggest this feature for me. I have no problem with editing the file or opening a console in my browser to change it. As said, I thought it would make sense before some admins are messing with the live instance.

**Comment by diafygi** [comment]
This project doesn't have "builds", so there's really not much to configure. It's a static website, so if you want to configure it differently, you need to just clone the repo, create a branch, and edit the files directly. That's what I do when I comment/uncomment the DIRECTORY_URL in the javascript when testing.
