### ISSUE TITLE
Error at step 3 : Provided agreement URL does not match current agreement URL 

### ISSUE THREAD

**Issue by soualid** [diafygi/gethttpsforfree#103]
Got the following error at Step 3, thank you in advance for your help !

> Error:
>  Account registration failed. Please start back at Step 1. { "type": "urn:acme:error:malformed", "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf]", "status": 400 }

**Comment by diafygi** [comment]
Thanks! Updated in 94028051c5cc181cfe960c7b7725c188d1448516. Can you please confirm the fix works?

**Comment by soualid** [comment]
Yes it is many thanks !
