### ISSUE TITLE
Renewal instructions

### ISSUE THREAD

**Issue by ki9us** [diafygi/gethttpsforfree#104]
Hi, I used your site, and it was very useful.  :+1:

Alas, I have no idea how to renew the cert.  It seems like [I'm not the only one](https://community.letsencrypt.org/t/how-to-manually-renew-a-certificate/11263/2).  Using an automated client like `letsencrypt-auto` seems like a bit of overkill if I can get a certificate by hand (gethttpsforfree-style).  I can just write a BASH script with cronjob and be on my way... 

So how do I renew the cert?  I gotta know in the next 90 days.  :open_mouth:

**Comment by diafygi** [comment]
There is now a note on renewal in v2.
