### ISSUE TITLE
Error: Account registration failed. Please start back at Step 1

### ISSUE THREAD

**Issue by sebyte** [diafygi/gethttpsforfree#109]
Hello diafygi,

I've been happily using https://gethttpsforfree.com for nearly a year now, i.e. I've been issuued an SSL cert three times without any problems at all.

This time however, I can't get beyond Step 2.  The error message (above) is displayed each time.

Nothing has changed at my end, and Step 1 appears to work fine.  It's only when I get to the end of Step 2 that I'm told to go back to Step 1.

Any ideas what the issue might be, or how I can go about debugging it?

Seb

**Comment by sebyte** [comment]
Hmm... today it worked fine.  I must have been doing something wrong, but I can't think what. Apologies for the noise.  And thanks for creating this facility in the first place!

**Comment by fuelflo** [comment]
Just in case it helps someone. I had the same problem. The issue was uMatrix blocking access to letsencrypt.
