### ISSUE TITLE
error at step 4

### ISSUE THREAD

**Issue by ghost** [diafygi/gethttpsforfree#111]
Step 4: Verify Ownership

In debian I only get empty.dir in the /acme-challenge/ directory

I uploaded the files to /var/www/html/.well-known/acme-challenge

and of course I get the error message when I click "I am now serving the files" button

**Comment by diafygi** [comment]
This usually happens when you are behind a firewall or something that is preventing the outside world from requesting that file (Let's Encrypt needs to request the file from their external servers).
