### ISSUE TITLE
Step 5 - Cannot find private key

### ISSUE THREAD

**Issue by R1im** [diafygi/gethttpsforfree#113]
After updating my httpd.conf

`

	SSLEngine on
    SSLCertificateFile    /etc/ssl/certs/domain.crt
    SSLCertificateKeyFile /etc/ssl/private/domain.key
    SSLCertificateChainFile /etc/ssl/certs/intermediate.pem
    SSLProtocol all -SSLv2 -SSLv3
    SSLCipherSuite ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA;
    SSLHonorCipherOrder on`

and restarting apache i get this

[Thu Dec 15 16:21:37.578386 2016] [ssl:error] [pid 15827] AH02203: Init: Private key not found

[Thu Dec 15 16:21:37.578473 2016] [ssl:error] [pid 15827] SSL Library Error: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag

[Thu Dec 15 16:21:37.578487 2016] [ssl:error] [pid 15827] SSL Library Error: error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error

[Thu Dec 15 16:21:37.578498 2016] [ssl:error] [pid 15827] SSL Library Error: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag

[Thu Dec 15 16:21:37.578509 2016] [ssl:error] [pid 15827] SSL Library Error: error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error (Type=RSA)

[Thu Dec 15 16:21:37.578522 2016] [ssl:error] [pid 15827] SSL Library Error: error:04093004:rsa routines:OLD_RSA_PRIV_DECODE:RSA lib

[Thu Dec 15 16:21:37.578532 2016] [ssl:error] [pid 15827] SSL Library Error: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag

[Thu Dec 15 16:21:37.578542 2016] [ssl:error] [pid 15827] SSL Library Error: error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error (Type=PKCS8_PRIV_KEY_INFO)

[Thu Dec 15 16:21:37.578548 2016] [ssl:emerg] [pid 15827] AH02312: Fatal error initialising mod_ssl, exiting

**Comment by diafygi** [comment]
This has to do with server configuration, not gethttpsforfree.com
