### ISSUE TITLE
Error at step 3

### ISSUE THREAD

**Issue by chancesmith** [diafygi/gethttpsforfree#114]
Everything goes smoothly up until this point. I'm not trying to add a `*` for a wildcard.
`Error: Domain failed. Please start back at Step 1. { "type": "urn:acme:error:malformed", "detail": "Invalid character in DNS name", "status": 400 }`

![SSL gethttpsforfree error at step 3 - DNS](http://sodiumhalogen.com/up_c/Screen%20Shot%202016-12-21%20at%205.41.38%20PM-xAgatLB9mt.png)

**Comment by mttsmmrssprks** [comment]
@chancesmith were you able to resolve this? I'm encountering a similar error messsage.

**Comment by diafygi** [comment]
Wildcards are now supported in v2.
