### ISSUE TITLE
Certificate signature failed status": 429

### ISSUE THREAD

**Issue by nedzad** [diafygi/gethttpsforfree#115]
Step 5: Install Certificate (Error: Certificate signature failed. Please start back at Step 1. { "type": "urn:acme:error:rateLimited", "detail": "Error creating new cert :: Too many certificates already issued for: stratoserver.net", "status": 429 })

**Comment by licaon-kter** [comment]
How many times  did you try lately?

**Comment by nedzad** [comment]
Maybe 5 times? because I had some problems in the beginning with the python webserver should I try again?

**Comment by nedzad** [comment]
i have tried again same problem :(

**Comment by licaon-kter** [comment]
This is rate limited do search "lets encrypt rate limit", you need to wait some days.

**Comment by nedzad** [comment]
Thank you. but are you sure this is my problem?

> You can create a maximum of 500 Registrations per IP Address per 3 hours. Hitting this rate limit is very rare.

I think the problem is that the domain i try to register is webservername.stratoserver.net and i think there are too many people who try the same.

**Comment by aureq** [comment]
@nedzad The error message is because there are too many already issued certificates for the domain `stratoserver.net`
