### ISSUE TITLE
When i run step 3 i am getting below error.

### ISSUE THREAD

**Issue by sidharthmm** [diafygi/gethttpsforfree#116]
Error: Domain failed. Please start back at Step 1. { "type": "urn:acme:error:rejectedIdentifier", "detail": "Policy forbids issuing for name", "status": 400 }

**Comment by licaon-kter** [comment]
What host exactly?

**Comment by sidharthmm** [comment]
HOST : ec2-54-161-216-146.compute-1.amazonaws.com

**Comment by licaon-kter** [comment]
One search away... https://community.letsencrypt.org/t/policy-forbids-issuing-for-name-on-amazon-ec2-domain/12692

/close as invalid
