### ISSUE TITLE
Why not combine step 3 into a single command to be run?

### ISSUE THREAD

**Issue by chrissound** [diafygi/gethttpsforfree#117]
So have just one input to be processed.

**Comment by hannob** [comment]
I'd like to second this request, just wanted to open a feature request myself.

I really like this tool for manual certificate generation, but the amount of manual steps is a bit annoying and it seems quite obvious to ease this by having the three sigs in step three done in a single step. Just let the user copy three commands in a row.

**Comment by diafygi** [comment]
This is because each section has to be individually signed by your openssl, so each command has to be run separately. I've updated this in v2 so it's not 3-at-once but rather unlocking each step one after the other.
