### ISSUE TITLE
Server responded with a status of 409 (Conflict)

### ISSUE THREAD

**Issue by progcode** [diafygi/gethttpsforfree#120]
Failed to load resource: the server responded with a status of 409 (Conflict)
acme-v01.api.letsencrypt.org/acme/new-reg

**Comment by progcode** [comment]
Found:  adblock issue (uBlock origin)

**Comment by anupammaurya** [comment]
Tried to private browser mode, and warning of that console(i.e. 409 error) is removed.
Problem with Adblocker here, some internal get request.. which are making conflict..

**Comment by sushcoder** [comment]
Failed to load resource: the server responded with a status of 409 (Conflict) for css file
what should i need to do to overcome this error

**Comment by diafygi** [comment]
There are no external css files with this project. I suspect you have a plugin or something that's injecting css.
