### ISSUE TITLE
Step 4: Make URL to verify ownership editable (e.g. https or another port)

### ISSUE THREAD

**Issue by jukey** [diafygi/gethttpsforfree#123]
In order to proceed in step 4 the signed token needs to be accessible from the outside. 

1. Does this only work with connections via http (port 80)? 

Unfortunately my webserver only can accessed by https and using port 1443.

2. Is there a way to make it happen even under these circumstances?
3. If yes, would it be possible to let me manipulate the URL before I use the "I'm now serving this file on hostname.tld" button?

**Comment by strifejester** [comment]
There is but I don't think solution can do it. You would need to create a valid DNS record for the response. I have not personally done this yet but reading your question has got me interested in doing it just to see how easy it is. If I come up with something I will replay again.

**Comment by strifejester** [comment]
This is from a comment on the letsencrypt community. Looks like I am going to be tearing into the source for this and seeing if I can make it happen.

At the simplistic level, the client talks to the Let's Encrypt ACME server and obtains a "token" that needs to be placed in a TXT record in your DNS. If your DNS provider has an API then this record can be added automatically, or you can do it manually. Once the TXT record is there, Let's Encrypt verifies this and provides you with a certificate (via the same client).

You will need a new token every time you need to renew for a new certifcate though, hence automation is easier.

**Comment by licaon-kter** [comment]
IIRC, for DNS at least, the token is the same for every renew (using the same CSR and domain key of course). Tested with https://zerossl.com/free-ssl/#crt

**Comment by willbprog127** [comment]
Greetings!  Has there been any progress on this?  My server only serves https and step 4 fails because it's expecting an http connection instead.

Thanks! :smile:

**Comment by diafygi** [comment]
Let's Encrypt always requests port 80 (but will follow 302 redirect responses from there). There is no way to change that since the must verify that you control that port to issue you a certificate.

**Comment by diafygi** [comment]
Actually, wait. Let's Encrypt also now allows a DNS verification. So you can use that option when doing the domain challenge.
