### ISSUE TITLE
step 3 problem.

### ISSUE THREAD

**Issue by globalaccess** [diafygi/gethttpsforfree#124]
When the instructions say copy and paste this code into your 'terminal', what exactly does the mean. I am on a windows box, so is that a command window or openssl command screen? Or something else, because I've tried both with no success.

**Comment by ThymoNL** [comment]
It's a Linux terminal command. I wouldn't know how to get that running on Windows.

**Comment by licaon-kter** [comment]
A package like   https://babun.github.io/ might help.

**Comment by efsant0s** [comment]
You need to change the terminology to windows, but still I wouldn't garantee it would work, change from
PRIV_KEY=./account.key; echo -n "eyJub[...]" | openssl dgst -sha256 -hex -sign $PRIV_KEY

to:
echo -n "eyJub[...]" | openssl dgst -sha256 -hex -sign account.key

After that select the text in the windows command prompt, copy and paste in a notepad, and delete ALL newline characters in the hex text. The text block should be a single line of text. And put the string “(stdin)= “ at the beginning of each line of hex-code. Note that there is a single space character between the equals sign and the start of the hex-code.

Best of luck
