### ISSUE TITLE
Styling changes.

### ISSUE THREAD

**Issue by sunnykgupta** [diafygi/gethttpsforfree#125]
I used this website to generate an SSL certificate for my Personal Blog.

I am a full-stack engineer with a focus on frontend engineering and would like to give back to the repo by helping style this webpage.

Opening this issue to see if the owner is open to accepting a pull request if I work on a slick visual overhaul of the page. Looking forward to helping out with the CSS changes.

**Comment by ojoven** [comment]
Hey Sunny,

I'm just a user of the project and I think that, though it's not actually necessary, some styling for the project could be interesting. Please let me know if you want any help or testing / feedback from my side if you finally implement any CSS changes to the site.

Cheers,
Mikel

**Comment by sunnykgupta** [comment]
Still waiting to hear from repo owner if they are willing to accept any CSS change.
If we do end up adding some CSS change, will surely keep you informed.

P.S - My portfolio to see work I've done previously: http://portfolio.icodestartups.com

**Comment by kenshub** [comment]
If you look at the end of the README.md, you will see that the intent is to keep the website simple.

I thought the page was broken, and had to dig around a bit before I decided to use it.

Maybe a couple lines of CSS to change the default font & page width for easier readability, and less people would assume the website is broken.

**Comment by diafygi** [comment]
Yes, you are welcome to fork the project if you want to restyle it, but I intentionally keep this website barebones as far as styling.
