### ISSUE TITLE
Root certificate

### ISSUE THREAD

**Issue by minhng99** [diafygi/gethttpsforfree#126]
It's better to show Root certificate once issued to complete the chain of trust

Root certificate: https://letsencrypt.org/certs/isrgrootx1.pem.txt

The Intermediate certificate X3 are: https://letsencrypt.org/certs/letsencryptauthorityx3.pem.txt
Backup Intermediate X4 certificate: https://letsencrypt.org/certs/letsencryptauthorityx4.pem.txt

**Comment by diafygi** [comment]
Let's Encrypt v2 now includes the intermediate certificate by default.
