### ISSUE TITLE
To everyone reading this

### ISSUE THREAD

**Issue by dylmye** [diafygi/gethttpsforfree#128]
This project still seems to be dead/non-functioning. Here is a small list of functioning (and easier) alternatives using Lets Encrypt:

- https://www.sslforfree.com    
- https://letsencryptonline.com    
- https://certbot.eff.org/

**Comment by licaon-kter** [comment]
Or https://zerossl.com/free-ssl/#crt
DNS FTW

**Comment by nightshark** [comment]
Thanks!

**Comment by diafygi** [comment]
@dylmye How is this project non-functioning? I just verified that it still works with my domain.

**Comment by diafygi** [comment]
Also, sslforfree.com letsencryptonline.com both appear to have access to or control your private key. THIS IS VERY DANGEROUS!

**Comment by dylmye** [comment]
@diafygi - #93 and the open non-responded issues and to a lesser extent the lack of recent commits - apologies if you are still active

**Comment by dylmye** [comment]
also, from sslforfree.com:

> For modern browsers we generate a private key in your browser using the Web Cryptography API and the private key is never transmitted. The private key also gets deleted off your browser after the certificate is generated. If your browser does not support the Web Cryptography API then the keys will be generated on the server using the latest version of OpenSSL and outputted over SSL and never stored.
