### ISSUE TITLE
Step 2

### ISSUE THREAD

**Issue by sudomatsu** [diafygi/gethttpsforfree#131]
While putting this in my bash:
openssl req -new -sha256 -key domain.key -subj "/"
  -reqexts SAN -config <(cat /etc/ssl/openssl.cnf
  <(printf "[SAN]\nsubjectAltName=DNS:mydomain.com,DNS:www.mydomain.com"))

It throws me an error:

cat: /dev/fd/63: No such file or directory

**Comment by diafygi** [comment]
I'm not sure how to help since /dev/fd/63 seems like it's unique to your system.
