### ISSUE TITLE
Step 3: Sign API Requests | openssl:Error: 'PRIV_KEY' is an invalid command.

### ISSUE THREAD

**Issue by krishnatrye** [diafygi/gethttpsforfree#133]
Hi ,

I am stuck on Step 3: Sign API Requests

I am using OpenSSL on Windows and getting below error while running this command.
PRIV_KEY=./account.key; echo -n "eyn0" | openssl dgst -sha256 -hex -sign $PRIV_KEY

Error : openssl:Error: 'PRIV_KEY' is an invalid command.

I checked previous issues as well and ran this command too but no help
set PRIV_KEY=account.key
(echo | set /p dummyName="ey...") | openssl dgst -sha256 -hex -sign %PRIV_KEY% -out out.sign

Please help asap

**Comment by sjurmr** [comment]
Skip the PRIV_KEY-stuff and enter the path to your key file directly at command prompt.
