### ISSUE TITLE
An alternative to verifying domain name ownership

### ISSUE THREAD

**Issue by ara303** [diafygi/gethttpsforfree#135]
I'm unable to get the verification files uploaded on my server (I use Surge.sh which ignores folders that begin with a dot). It would be really good if there was another way to prove ownership of a domain.

SSLforFree.com allow the use of a TXT DNS record on the domain to verify ownership. This seems like it would be awesome because it's something I could set and forget about. For example when verifying a domain with Google's admin tools, it is easier to use a TXT DNS record than to put a file in the root directory.

Is it possible that this could use an alternative method to verify that does not not involve writing files to the server?

**Comment by licaon-kter** [comment]
You can use DNS, via https://zerossl.com/free-ssl/#crt

**Comment by ara303** [comment]
Thanks @licaon-kter , didn't know about that ...Just found out my host doesn't support uploading custom certs after all. :( This will still be useful in the future.
