### ISSUE TITLE
Step 3: Sign API Requests Error

### ISSUE THREAD

**Issue by tsatatwer** [diafygi/gethttpsforfree#136]
I get this error:
Error: You need to run the above commands and paste the output in the text boxes below each command.
I used this :  echo|set /p="eyJ..SNIP..In0" | openssl dgst -sha256 -hex -sign account.key
I searched all hidden linebreaks/whitespace and removed them with Notepad++ .

  
![step 3 error](https://user-images.githubusercontent.com/19878047/30636982-f1bf5dee-9dee-11e7-8683-0c39c60799ef.jpg)

**Comment by diafygi** [comment]
This shouldn't happen any more in v2. Please open a new issue if you're still seeing this error.
