### ISSUE TITLE
Tagged releases and changelog

### ISSUE THREAD

**Issue by baimafeima** [diafygi/gethttpsforfree#137]
Could you tag your releases and make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by licaon-kter** [comment]
What releases?

**Comment by baimafeima** [comment]
https://github.com/diafygi/gethttpsforfree/releases

**Comment by licaon-kter** [comment]
What does this project need to release on that page?

The site is a live, up to date version of the repo: https://gethttpsforfree.com/

Yes, that would be useful if this would be developed further, but it's kinda not. Eg. https://zerossl.com/free-ssl/#crt has DNS validation already.

/close as invalid

**Comment by diafygi** [comment]
The actual website (https://gethttpsforfree.com/) is just a reverse proxy of the Github Page for this repo, so what you see in the repo is what is always what is available on the website.
