### ISSUE TITLE
Error: Certificate signature failed. Please start back at Step 1.

### ISSUE THREAD

**Issue by Marow** [diafygi/gethttpsforfree#138]
Hi, i tried to use gethttpsforfree...

All good but Step5 get this ERROR

`Error: Certificate signature failed. Please start back at Step 1. { "type": "urn:acme:error:malformed", "detail": "Error creating new cert :: certificate public key must be different than account key", "status": 400 }`

But i dont know what is wrong here... 
Created certificate with this command
`sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt`

**Comment by diafygi** [comment]
There are two keypairs you need to use for Let's Encrypt: (1) your "account" keypair (2) your "domain" keypair. The "account" keypair is used to sign requests to Let's Encrypt. The "domain" keypair is the certificate you're actually trying to have validated and signed by Let's Encrypt. You can't use the same keypair for both "account" and "domain".
