### ISSUE TITLE
Renewal certification without root privilege

### ISSUE THREAD

**Issue by john200999** [diafygi/gethttpsforfree#139]
I host as [ Economy Linux Hosting with cPanel ] on Godaddy  , I have no root privilege and can not modify Apache configuration files even start or stop the httpd daemon.

However, I use file method at [ Step 4 ] , successfully manually install the certification on server. This project is really doing a great great great favor to me.

I will deeply appreciate if the renew.html and revoke.html can be worked out in the near future.

**Comment by licaon-kter** [comment]
Even as non-root you can setup cron jobs, right?

**Comment by john200999** [comment]
Yes, cron jobs are allowed, but only with no su needed commands.

**Comment by licaon-kter** [comment]
How do you setup the certs without root in your case?

**Comment by john200999** [comment]
The server supports SSH and openssl, and a web page contains four CA functions :
(1) Generate, view, upload, or delete private keys.
(2) Generate, view, or delete SSL certificate signing requests.
(3) Generate, view, upload, or delete SSL certificates.
(4) Install and Manage SSL (HTTPS)

Below are what I done
[Step 1]
I generate a private key by using server function (1), and copy it into my home folder as account.key

[Step 2]
I generate a CSR by using sever function (2), copy it into gethttpsforfree's text box for validation

[Step 3]
I've copied an account.key in my home folder,  I use SSH to run bash commands on it

[Step 4]
I choose using file-base method, copy the signature file into proper directory for Let's encrypt server to verify

[Step 5]
Success !   Thanks to gethttpsforfree !
Then I upload CA to server by using sever function (3),
Activate HTTPS by using sever function (4)

There are some points in whole process
(1). I do not know where does the server save the private key and the certificates , I tried .... no permission ....
(2). I can not directly modify Apache configuration files
(3). I can not manually start or stop httpd daemon
(4). The cPanel which server provide is a reduced version. I've asked GoDaddy, add a HTTPS service will be more easy if I pay double ,..

**Comment by licaon-kter** [comment]
Ok, if it's a web based menu (cantrol panel of sorts) that you use to update the certs, then you can't use any auto update method. You need root shell access.

/Close this as invalid

**Comment by john200999** [comment]
Is there any way to make renewal process easier ?
In my case, seems I need to start from Step 1 to Step 5 on gethttpsforfree again ?

**Comment by licaon-kter** [comment]
If you can edit DNS entries this is faster, since they mostly stay the same, so generate the certs here instead: https://zerossl.com/free-ssl/#crt

**Comment by john200999** [comment]
Thanks a lot, you are an excellent adviser.
