### ISSUE TITLE
Error while Validating Signatures

### ISSUE THREAD

**Issue by ndhambi** [diafygi/gethttpsforfree#141]
I keep getting this error when i try validate the signatures (Step3 on https://gethttpsfree.com)

Error: Account registration failed. Please start back at Step 1. { "type": "urn:acme:error:badNonce", "detail": "JWS has invalid anti-replay nonce Hjmjx7usi9Eo_hroR1rStJgDDIdONvBbkFc2HI85SdA", "status": 400 }

**Comment by licaon-kter** [comment]
What OS do you run openssl on?

**Comment by ndhambi** [comment]
I want to create the certificate for an ubuntu server 16.04 but i am running  the getthttpsfree.com on a windows 10 chrome browser

**Comment by licaon-kter** [comment]
But the commands, where do you run them?

**Comment by diafygi** [comment]
This shouldn't happen anymore in v2 since we get anti-reply nonces each time so you don't have to rush through the steps. Please open another issue if you are still seeing this.
