### ISSUE TITLE
Action required: Let's Encrypt subscriber agreement URL Change

### ISSUE THREAD

**Issue by cpu** [diafygi/gethttpsforfree#144]
Hi there,

I just opened https://github.com/diafygi/acme-tiny/issues/188 on the acme-tiny repository. That issue also affects this project:
https://github.com/diafygi/gethttpsforfree/blob/706d854646735612196f37c816d20aaac048e05d/js/index.js#L8

Please refer to https://github.com/diafygi/acme-tiny/issues/188 for details & suggested fixes.

**Comment by diafygi** [comment]
FYI, I'm going to review this stuff ASAP to make sure the TOS link change works.

**Comment by diafygi** [comment]
fixed in https://github.com/diafygi/gethttpsforfree/commit/30e1a0baaa1bfd6001d57a7301dba1eeb4edfe23
