### ISSUE TITLE
Feature request: automatic copy to clipboard in OSX

### ISSUE THREAD

**Issue by poisa** [diafygi/gethttpsforfree#148]
It would be great to have a checkbox somewhere that would use "pbcopy" for people who will run the generated commands in OSX.

When you check this option, all the commands generated by gethttpsforfree would end with 
`| pbcopy`. In OSX, this copies the output of the previous command to the clipboard thus alleviating the user from having to precisely select the output text in the terminal.

Not sure if this exists in Linux distros that's why I suggested it as an optional setting for people who use OSX.

**Comment by diafygi** [comment]
I'd rather do something similar to a "click-to-copy" like in #142

**Comment by rgsteele** [comment]
#142 is for copying from the browser to the terminal. This request is for copying from the *terminal* to the *browser*. 

Equivalent commands for Linux can be found at [this StackExchange post](https://stackoverflow.com/questions/749544/pipe-to-from-the-clipboard-in-bash-script).
