### ISSUE TITLE
Bad path to openssl.cnf when on CentOS 6

### ISSUE THREAD

**Issue by kostich** [diafygi/gethttpsforfree#15]
Hi. At the step 2 (Certificate signing request), you advise using the following for generating csr on Linux:

> openssl req -new -sha256 -key domain.key -subj "/" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf "[SAN]\nsubjectAltName=DNS:foo.com,DNS:www.foo.com"))

This won't work on CentOS and RHEL because the path to the openssl.cnf isn't this but `/etc/pki/tls/openssl.cnf`.

Maybe rework the site so it shows the instruction for both Debian and RedHat Linux families?

**Comment by diafygi** [comment]
Thanks!

**Comment by josephlhall** [comment]
Heya, I ran into this while writing up how non-root users can get an LE cert in a cPanel/WHM hosting environment (we do a lot of work to try and make technical things less technical).

It would be good to add a caveat in the text of the instructions in README.md that mirrors what you have in the source... I'm happy to craft a PR if you'll take it.
