### ISSUE TITLE
Instructions for installing certificates are out of date

### ISSUE THREAD

**Issue by thierer** [diafygi/gethttpsforfree#152]
In the version currently served from https://gethttpsforfree.com (I guess that's current HEAD?) the inline instructions for the "Install Certificate" step ("how do I install this?") seem out of date.

The website *used* to show the domain and the intermediate certs in two different fields but now both are in the same textarea, so the instructions referring to separate results and concatenating them don't make sense any more. Also, I think it would be useful to point out that the first certificate is the domain certificate (if that's deterministic, which I would guess) because people might want to split them.

**Comment by diafygi** [comment]
Updated the text and specified which certificate section was which in the apache instructions.

See diff here: https://github.com/diafygi/gethttpsforfree/commit/582029ea4c3d7f1a20c6a155e7e367a3de5ed017
