### ISSUE TITLE
Guidance re wildcard certs

### ISSUE THREAD

**Issue by raphaelokon** [diafygi/gethttpsforfree#155]
Hi there.

I think it would be awesome to have a explainer section in the CSR generation section regarding wildcard certs (is that even possible with _gethttpsforfree_?)

Happy to do a PR.

**Comment by gkarag** [comment]
This worked for me:
`openssl req -new -sha256 -key domain.key -subj "/CN=*.foo.com" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf "\n[SAN]\nsubjectAltName=DNS:foo.com" `

**Comment by raphaelokon** [comment]
Thanks @gkarag

**Comment by OnlineGBC** [comment]
Minor typo fix.  The code should have two )) at the end like this:
openssl req -new -sha256 -key domain.key -subj "/CN=*.onlinegbc.com" -reqexts SAN -config <(cat /etc/pki/tls/openssl.cnf <(printf "\n[SAN]\nsubjectAltName=DNS:onlinegbc.com"**))**
