### ISSUE TITLE
We translated gethttpsforfree into Chinese.

### ISSUE THREAD

**Issue by 92hackers** [diafygi/gethttpsforfree#157]
Hi there,
We noticed that [gethttpsforfree](https://gethttpsforfree.com/) has not been translated to Chinese. We translated it into Chinese. Click here: [translation](https://translate.breword.com/pages/d5d2e95d515140f3a345fe17e8405296) . 
See pull request here: #156

**Comment by diafygi** [comment]
Thanks! However, it looks like your website's certificate has expired.
