### ISSUE TITLE
Error on Step 4: Verify Ownership

### ISSUE THREAD

**Issue by vishvega** [diafygi/gethttpsforfree#159]
Everytime I went to final stage on step 4, I get this message. what can I do to fix this and get the certificate? please help.

> Error: Domain challenge failed. Please start back at Step 1. {"identifier":{"type":"dns","value":"mysite.com"},"status":"invalid","expires":"2018-08-22T12:10:01Z","challenges":[{"type":"tls-alpn-01","status":"invalid","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/nWM48Eadja6w6UabmZvj-F7DnumyGhgMvfG7qcmqXmI/6494740744","token":"vsDIAcOnwhzFxffvRyuZsIaUNbgC0C7B2wrApPYN18s"},{"type":"http-01","status":"invalid","error":{"type":"urn:ietf:params:acme:error:unauthorized","detail":"Invalid response from http://mysite.com/.well-known/acme-challenge/gzpLO2apOiPhrJM4xybuhZkc2wSTbF9hKzY9hN78dJ4: \"<html><body><script type=\"text/javascript\" src=\"/aes.js\" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,func\"","status":403},"url":"https://acme-v02.api.letsencrypt.org/acme/challenge/nWM48Eadja6w6UabmZvj-F7DnumyGhgMvfG7qcmqXmI/6494740745","token":"gzpLO2apOiPhrJM4xybuhZkc2wSTbF9hKzY9hN78dJ4","validationRecord":[{"url":"http://mysite.com/.well-known/acme-challenge/gzpLO2apOiPhrJM4xybuhZkc2wSTbF9hKzY9hN78dJ4","hostname":"mysite.com","port":"80","addressesResolved":["185.27.134.217"],"addressUsed":"185.27.134.217"}]},{"type":"dns-01","status":"invalid","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/nWM48Eadja6w6UabmZvj-F7DnumyGhgMvfG7qcmqXmI/6494740746","token":"yft8Muq8WJMd97W58ENJm4Q0v7EBDRZIyj6rF1jOvFg"}]}

**Comment by thierryc** [comment]
same

**Comment by diafygi** [comment]
`Invalid response from http://mysite.com/.well-known/acme-challenge/gz...`

This indicates that when Let's Encrypt tried to request that file, it couldn't connect or the file didn't contain the challenge text.
