### ISSUE TITLE
Locally hosted semi-automated operation for externally hosted cert renewals

### ISSUE THREAD

**Issue by vtgit** [diafygi/gethttpsforfree#161]
First let me say that your website code is an absolute gift to us, who are presently staying with a host lacking Let's Encrypt automation! Thank you!

I'm posing this only as a suggestion:.....I'd love to be able to run this in semi-automated fashion locally to generate renewal certs for my externally hosted domains. My host doesn't support Let's Encrypt, other than allowing me to place the Cert and key on the website via ftp. I don't have shell access there, and can't run Certbot. This means manual renewal every 90 days, and I have multiple domains.

I don't mind generating renewal certs locally on my own machine, and then uploading if I could do that more easily with fewer cut-and-paste steps between your code, the console, and a text editing program to create the necessary named challenge files. 

I don't mean total automation, (eg, not asking to have the program ftp the files) but some streamlining, of the file generation process when running the program locally. 

It's not bad for a single domain, but I have several add-on domains, and creating those files for each before generating a single overall cert is really difficult. It's easy to get confused about the clipboard contents while cutting and pasting, and saving multiple oddly named files, etc.

I don't know exactly know how you'd script it differently for a local machine -- but it seems like running terminal commands, and cutting and pasting could be performed by the program, with an automated output of the challenge files in appropriate local folders named by domain. Then the user could manually ftp those up to his/her website, and apply for the cert.

Even some kind of macro function that the user could have to automate data entry/file generation would be a great help. I don't know how feasible that is. Just a thought.

**Comment by diafygi** [comment]
This website is intended for manually getting certs. If you want to automate it, I'd recommend using another project specifically designed for automation. For example, I use my own [acme-tiny](https://github.com/diafygi/acme-tiny) script for automated certificate signing.

**Comment by diafygi** [comment]
Also, if you want semi-automation, maybe take a look at my [acme-nosudo](https://github.com/diafygi/acme-nosudo) project?
