### ISSUE TITLE
Node.js package and longer periods of time ?

### ISSUE THREAD

**Issue by rraallvv** [diafygi/gethttpsforfree#162]
I've been using gethttpsforfree on the website, it's very helpful. I wonder if all the steps could be added to a Node.js package to use as an interactive script, and also what should it take to add a field to specify the time for the certificate. Keep the good work.

**Comment by rraallvv** [comment]
This is what I get when trying to use cerbot
```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
NOTE: The IP of this machine will be publicly logged as having requested this
certificate. If you're running certbot in manual mode on a machine that is not
your server, please ensure you're okay with that.

Are you OK with your IP being logged?
```
That's why I wanted a way to do the process that gethttpsforfree.com does but automatically from a Node.js script

**Comment by diafygi** [comment]
I do not plan on packaging this for node.
