### ISSUE TITLE
Unauthenticated resource GETs on ACME v2

### ISSUE THREAD

**Issue by testtlnls** [diafygi/gethttpsforfree#165]
Hi.
Thank you for your great tool.

Your tool looks like using GET method to get authorization now.

According to https://community.letsencrypt.org/t/acme-v2-scheduled-deprecation-of-unauthenticated-resource-gets/74380,
After November 1st, 2020, it will disallowed.
We can test it on the staging now.

Please replace from GET to POST-as-GET.

Thank you.

**Comment by diafygi** [comment]
Thanks for letting me know. I want to support the change, so will have this fixed by the deadline.

**Comment by daniel-utilityapi** [comment]
@testtlnls created a get-as-post branch and pull request. Please see if it works for you.

**Comment by diafygi** [comment]
@testtlnls created a get-as-post branch and pull request (#168). Please see if it works for you.

**Comment by testtlnls** [comment]
Thank you for your reaction.
I'm sorry for late reply and forgotten another bug report.

index.html on the branch worked well on the staging.
I will test it on production tomorrow because I don't have no more time to test on production today.

Now, I want to report another bug which is not critical.

We cannot order certificates including domains valid with tls-alpn-01 on staging / production ACME v2 with your tool now.
This problem is not critical because it can be avoided with new account.

Thank you.

![challenge-management-bug](https://user-images.githubusercontent.com/41869011/76365993-0df50280-636c-11ea-92bb-785bdcc35f68.png)

**Comment by diafygi** [comment]
@testtlnls I'm not aware of situations where tls-alpn-01 is the only option. What causes the situation where http and dns challenge options are not available?

**Comment by testtlnls** [comment]
Processing stops caused by unavailable of http and dns happen on domains already valid with tls-alpn-01 on the account.
The official announcement is following.
https://community.letsencrypt.org/t/acme-v1-v2-changing-challenges-returned-for-invalid-valid-authorizations/107661

For example, I got a certificate for example.com with tls-alpn-01. Then, I will try getting a certificate for example.com and *.example.com with your tool and same account. It will be failed.

In fact, dns-01 only case also has bug which has no effect : considered as wildcard

In this situations, options are running proposed valid validation method or skipping the validations. Of course pending validations which has option(s) as usual must be run.

Thank you.

**Comment by diafygi** [comment]
@testtlnls I've been using the `get-as-post` branch for a few months now, and it's working regularly for me. So I've merged it into the production website.
