### ISSUE TITLE
Step 4: Verify Owner Keeps Failing

### ISSUE THREAD

**Issue by gknextlevel** [diafygi/gethttpsforfree#169]
When I get to step 4 Verify Owner and do the first challenge. I upload the ACME verification file to my website, paste the hex and it works fine. 

But after that it doesn't show me the next ACME verification file to upload to my website. It just shows the next challenge. I thought ok I was expect the next ACME verification file. Nevertheless, I provide the hex. It then gives me an error that basically says I didn't find the ACME verification file on my website. I tried several times.

Also, is there a time limit on how long you have to complete the process?

**Comment by dduraipandian** [comment]
I also ran into the issue.

**Comment by gknextlevel** [comment]
I never got it work. I ended up using: certify the web dot com

It took me a little while to get that working because I had and old server (windows 2003). lol... Soon after I upgraded my server and creating the certificate using this website. It was super easy. Hope this helps you create a free certificate too.
