### ISSUE TITLE
Unable to access https://gethttpsforfree.com

### ISSUE THREAD

**Issue by kajihara-kenji** [diafygi/gethttpsforfree#181]
ERR_CONNECTION_REFUSED is displayed 
Is there something wrong?

**Comment by Jbarela505** [comment]
> ERR_CONNECTION_REFUSED is displayed Is there something wrong?

I too am getting this. I know last week was a holiday for the US, but hoping the site issues are resolved quickly! I have a 8 certs expiring tuesday and I'm freaking out a little bit.

**Comment by Jbarela505** [comment]
Its back up!

**Comment by diafygi** [comment]
Howdy, sorry, my VPS provider decided to restart the machine just as I went on holiday for Thanksgiving.
