### ISSUE TITLE
Site offline

### ISSUE THREAD

**Issue by Jbarela505** [diafygi/gethttpsforfree#182]
Unable to access the site. Error below presents. Was it taken offline intentionally? 

This site can’t be reachedgethttpsforfree.com refused to connect.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

**Comment by diafygi** [comment]
Howdy, sorry, my VPS provider decided to restart the machine just as I went on holiday for Thanksgiving.
