### ISSUE TITLE
Set the default branch to gh-pages?

### ISSUE THREAD

**Issue by karlhorky** [diafygi/gethttpsforfree#19]
Instead of having to keep identical `master` and `gh-pages` branches up to date, some projects (like [gray](https://github.com/karlhorky/gray)) choose to set the default branch to `gh-pages`. You can change this under [Settings > Branches](https://github.com/diafygi/gethttpsforfree/settings/branches). You can then delete the master branch.

![bildschirmfoto 2015-12-04 um 19 32 41](https://cloud.githubusercontent.com/assets/1935696/11597883/e1889f7e-9abe-11e5-8190-b233ea27b550.png)

Ref: [GitHub Docs](https://help.github.com/articles/setting-the-default-branch/)

**Comment by diafygi** [comment]
Good idea, done

**Comment by rayshan** [comment]
Hi, I assume https://gethttpsforfree.com/ is served directly from gh-pages? It may be a good idea to show a version number somewhere so the user knows she's using the latest.

**Comment by diafygi** [comment]
Yes, gethttpsforfree.com is just a reverse-proxy, the user can assume the code in this repo is what is on the website.

**Comment by rayshan** [comment]
Thanks :+1:

**Comment by karlhorky** [comment]
Cool, thanks for this great project :)
