### ISSUE TITLE
Step 4 doesn't reset when generating multiple certs

### ISSUE THREAD

**Issue by bronson** [diafygi/gethttpsforfree#22]
I used gethttpsforfree.com to generate multiple certs (u32.net, www.u32.net, etc)...

First I went through the whole process for `u32.net`.  Couldn't have gone better.

Then, I started over at step 2 to create a cert for `www.u32.net` (server sw won't let me combine them).  When I reached step 4, gethttpsforfree still thought we were working with u32.net.  Clicking Submit ("I'm now serving this file on u32.net") failed after a while, then everything reset and I was able to generate the file for www.u32.net.

So, everything works, it's just unfortunate that it needs to timeout once first.

Since this is the biggest problem I ran into, gethttpsforfree is working extraordinarily well.  Great job.

**Comment by diafygi** [comment]
Yeah, for multiple uses, it's probably best to refresh the page (which clears all the variables). Always welcome to review pull requests that fix any race conditions!
