### ISSUE TITLE
Start back at Step 1 we have too many requests for this url

### ISSUE THREAD

**Issue by V3r0x** [diafygi/gethttpsforfree#25]
Step 5: Install Certificate (Error: Certificate signature failed. Please start back at Step 1. {"type":"urn:acme:error:rateLimited","detail":"Error creating new cert :: Too many certificates already issued for: no-ip.org","status":429})

cool .... 

why ?

**Comment by licaon-kter** [comment]
Wait a bit: https://github.com/letsencrypt/letsencrypt/issues/1607#issuecomment-162106898

**Comment by V3r0x** [comment]
wow ty for quick reply. then i ll cname in my domain via no-ip.

many thx again
