### ISSUE TITLE
Step 4 fails on IPv6-only server

### ISSUE THREAD

**Issue by m-ad** [diafygi/gethttpsforfree#28]
I am at step 4 option 2, the challenge file is there (can access it with my browser) with the right content but I receive this error (X-ed my domain name):

> Error: Domain challenge failed. Please start back at Step 1. {"type":"http-01","status":"invalid","error":{"type":"urn:acme:error:unknownHost","detail":"No IPv4 addresses found for XXXXX"}

My server is indeed only accessible via IPv6 and has no IPv4 address (stupid carrier-grade NAT). Apparently this is a known bug in letsencrypt: https://github.com/letsencrypt/letsencrypt/issues/180 and https://github.com/letsencrypt/letsencrypt/issues/1466 
Until they fix that issue over there, I propose a rewrite of the error message, especially not "Please start back at Step 1" because that would be wasted time.

Unfortunately, the python-based challenge doesn't work too: I can't connect to the webserver at all. With a tweak to the python commands (via https://github.com/letsencrypt/letsencrypt/issues/1466#issuecomment-156554125) I can at least get the server to be accessible:

``` python
import BaseHTTPServer, SimpleHTTPServer, socket
h = BaseHTTPServer.BaseHTTPRequestHandler
SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map = {'': 'text/plain'}
class HttpServerV6(BaseHTTPServer.HTTPServer):
    address_family = socket.AF_INET6

h.do_GET = lambda r: r.send_response(200) or r.end_headers() or r.wfile.write(XXXXX')
s = HttpServerV6(('', 80), SimpleHTTPServer.SimpleHTTPRequestHandler)
s.serve_forever()
```

I can now connect to the webserver, but only to receive an Error 404 page. I have not enough experience with these python HTTPServers, but might it be possible to get the challenge to work at least with the python-based option?

**Comment by diafygi** [comment]
This is a bug with the Let's Encrypt certificate authority software itself. See https://github.com/letsencrypt/boulder/issues/593
