### ISSUE TITLE
Replace genrsa with genpkey

### ISSUE THREAD

**Issue by dol** [diafygi/gethttpsforfree#3]
According to the [OpenSSL documentation](https://www.openssl.org/docs/manmaster/apps/openssl.html) the genrsa command is superseded by [genpkey](https://www.openssl.org/docs/manmaster/apps/genpkey.html)

E.g.:

```
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096
```

**Comment by diafygi** [comment]
Eh, it's a bit more complex of a command, so I'll stick with genrsa until Let's Encrypt starts accepting elliptic curve public keys.

**Comment by dol** [comment]
If you copy paste it, it not an argument about the complexity of the command. But it your decision.
