### ISSUE TITLE
Step 4 lists "old" entries on error

### ISSUE THREAD

**Issue by code28** [diafygi/gethttpsforfree#31]
When an error occured in step 4, it says "Please go back to Step 1", but when starting from step 1, the domain(s) will be appended in step 4 again, so they appear multiple times.

Possibly previous domains could be detached before appended (or just replaced). Here is the code I'm talking about:

```
// append this domain to step 4
template.id = "challenge_" + d_;
template.style.display = null;
document.getElementById("challenge_domains").appendChild(template);
```

**Comment by diafygi** [comment]
Howdy, I'm unable to reproduce this. Can you please give me a specific list of detailed steps to reproduce this? Thanks!

**Comment by code28** [comment]
Hey.
Just complete steps 1 to 3 exactly as described, but twice _without refreshing the page_.
When step 3 says for the second time "Step 3 complete! Please proceed to Step 4.", you have the domains twice at step 4.
This is of course quite unusual usage, but in case of an error in step 4, you're told to go back to step 1 and then this appears as well.

This is my result of doing steps 1 to 3 twice. Actually, here should only be 2 entries instead of 4:
![4 Domains, foo.com and www.foo.com each twice](https://cloud.githubusercontent.com/assets/7918047/11722005/edab60d2-9f66-11e5-8403-fc517dbca9f8.png)

I hope I could clarify the issue.

**Comment by diafygi** [comment]
I think I fixed this in 6900417, can you please confirm?

**Comment by code28** [comment]
Yes, this issue is fixed, but another error occurs: For each added domain, the _whole section_ is cleared, so only the last domain is shown, if the request contains more than one domain.

I'm not that much into JavaScript, but maybe something like this would do it: (The 4th line is added, replacing line 634)

```
// append this domain to step 4
template.id = "challenge_" + d_;
template.style.display = null;
document.getElementById("challenge_domains").removeChild(document.getElementById(template.id));
document.getElementById("challenge_domains").appendChild(template);
```

**Comment by diafygi** [comment]
@code28 gotcha, I'd rather clear everything at the start. How about now?

**Comment by code28** [comment]
That's it, great!
