### ISSUE TITLE
Step 5 throws error immediately

### ISSUE THREAD

**Issue by schmidt3d** [diafygi/gethttpsforfree#33]
After successfully completing step1-4  the final step 5 throws
immediately an error:

Step 5: Install Certificate (Error: Certificate signature failed.
Please start back at Step 1.
{"type":"urn:acme:error:malformed","detail":"Unable to read/verify
body :: JWS verification error","status":400})

**Comment by TrooperMaXX** [comment]
same here

**Comment by diafygi** [comment]
Howdy, I've added a debug mode. Can you please visit https://gethttpsforfree.com/?debug and try this again. When it shows an error, can you please open your console and copy and paste what's in there? Thanks!

**Comment by TrooperMaXX** [comment]
I think we both got this thing working some how but thank you so much for the debug link :) :+
