### ISSUE TITLE
Something went wrong. Go back to Step 1

### ISSUE THREAD

**Issue by schmidt3d** [diafygi/gethttpsforfree#34]
When something goes wrong you have to start at the beginning. That's not very helpful. It would be great to get some idea what exactly went wrong and restore as much as possible of the previous progress.

**Comment by licaon-kter** [comment]
Yes this needs some improvements, maybe actually showing the error too, instead of hunting it down in the browser console.

**Comment by diafygi** [comment]
The error message should contain extra information about what exactly went wrong. Do you have a specific example that I can try and reproduce?

Also, I've added a debug mode to print the current global state to console, which will allow for easier troubleshooting. Just add ?debug to your url and it will print the global variables to the console before clearing them.
