### ISSUE TITLE
Step 2: Process Substitution not generally supported

### ISSUE THREAD

**Issue by schmidt3d** [diafygi/gethttpsforfree#35]
Process substitution is not generally supported by all shells. Running Step 2 in busybox on a Synology NAS, I had to use a work around using temporary files.
Maybe it makes sense to change this in order to make the shell code more general?

**Comment by TrooperMaXX** [comment]
hey i have the same problem with our NAS can u show me the workaround :)

**Comment by schmidt3d** [comment]
Sure!

printf "[SAN]\nsubjectAltName=DNS:foo.com,DNS:www.foo.com" >tmp1
cat /etc/ssl/openssl.cnf tmp1 >tmp2
openssl req -new -sha256 -key domain.key -subj "/" -reqexts SAN -config tmp2
rm tmp1
rm tmp2

**Comment by diafygi** [comment]
Thanks for the note, but CSR generation gotchas are a bit out of scope for this project. If you have a special environment, adjust the help text as needed. The help text is only there to give you suggested commands, not cover all edge cases.
