### ISSUE TITLE
Step 3: last command too long

### ISSUE THREAD

**Issue by schmidt3d** [diafygi/gethttpsforfree#37]
In Step 3 the last command was too long for my ssh client (putty on Windows). The terminal cropped the command, so it failed.

**Comment by licaon-kter** [comment]
What shell?

**Comment by TrooperMaXX** [comment]
putty

//sry 
//I am ashamed

**Comment by licaon-kter** [comment]
Putty is not a shell.

Maybe paste the command in a text file and run **sh ./yourfile** ?

**Comment by schmidt3d** [comment]
The shell is BusyBox v1.16.1.

It seems to cut off after 1046 characters. Starting a script with the long command works, but it's cumbersome. Maybe the generated code can contain line breaks or split very long commands into several commands.

I am able to paste the full command into a file using putty, so the problem is caused by the shell and not by putty.

**Comment by licaon-kter** [comment]
Maybe try in a Linux VM in VirtualBox or get https://babun.github.io

**Comment by schmidt3d** [comment]
Well, as I wrote, I've found a work around and solved the issue for me. I'm just putting this here to see if there's interest in extending the code to make it work on more systems out of the box.

**Comment by diafygi** [comment]
Good to know, but there's not really anything I can do to fix this. The signature payload can't be shortened, so not sure what you want me to do.
