### ISSUE TITLE
SSLCertificateFile doesn't support chained certificates in Apache 2.2 

### ISSUE THREAD

**Issue by thierer** [diafygi/gethttpsforfree#39]
Just a quick heads up regarding the configuration instructions for Apache: 

The suggestion to concatenate the domain and the intermediate certificate doesn't work for Apache 2.2. The [docs suggest this feature was added in version 2.4.8](http://httpd.apache.org/docs/2.4/en/mod/mod_ssl.html#sslcertificatefile).

The correct configuration for Apache 2.2 seems to be

```
SSLCertificateFile          /etc/ssl/certs/domain.pem
SSLCertificateChainFile     /etc/ssl/certs/intermediate.pem
```

There's no warning when configuring Apache 2.2 as suggested, it just doesn't work as intended.

**Comment by licaon-kter** [comment]
This: https://github.com/diafygi/gethttpsforfree/pull/36 ?

**Comment by thierer** [comment]
Yes, missed that, thanks for the pointer. I'll still leave this open until the PR is merged.

**Comment by diafygi** [comment]
Fixed and merged.
