### ISSUE TITLE
Can't sign *.domain.com

### ISSUE THREAD

**Issue by Ahuahuachi** [diafygi/gethttpsforfree#40]
Not sure if this an api issue or an issue of this tool but it seems that you can't use wildcards when you try to sign your requests.
Tried to sign *.mydomain.com   <--Obiously thats not my domain
but instead had to sign www.mydomain.com, mydomain.com and all my subdomains

**Comment by ElliotGluck** [comment]
Currently, Let's Encrypt does not support wildcard certs, but they may implement it in the future.

Refer to https://github.com/letsencrypt/letsencrypt/issues/66
