### ISSUE TITLE
not a trusted authority

### ISSUE THREAD

**Issue by TrooperMaXX** [diafygi/gethttpsforfree#41]
"The certificate was issued by Let's Encrypt Authority X1, which is not a trusted authority. 

This is most likely because the servers' certificate chain is not installed correctly."
-https://www.wormly.com/test_ssl/h/hoell.syno-ds.de/i/5.158.136.15/p/55443

what did i wrong

![cert](https://cloud.githubusercontent.com/assets/2643418/11711041/f68d5a9a-9f23-11e5-9d03-d639bfc93149.png)

**Comment by licaon-kter** [comment]
https://www.ssllabs.com/ssltest/analyze.html ?

**Comment by TrooperMaXX** [comment]
wont work because my https is on the port 55443 not 443

**Comment by licaon-kter** [comment]
Oh ok ( use :55443 )
- https://sslanalyzer.comodoca.com/
- https://www.digicert.com/help/

Yes they both say the same, now, is that a Synology something? See this [post #15](https://community.letsencrypt.org/t/synology-nas-using-le-as-a-ca-signing-authority/453/15)

**Comment by TrooperMaXX** [comment]
thank you very much ♥ 
that post helped me alot :) :+1: 
now it works thanks alot :))))))
