### ISSUE TITLE
No external files

### ISSUE THREAD

**Issue by alexs77** [diafygi/gethttpsforfree#42]
It would be cool, if the site would only have ONE (large) HTML file. This would make it even easier to simply do a "Save As…" and have everything running right away.

At the moment, at least Chrome creates a subfolder with some .js Javascript files. Couldn't those files all be merged into the .html HTML file?

**Comment by diafygi** [comment]
Sorry, that reduces auditability. Most major browsers have a Save Complete Website option when you right click and save.
