### ISSUE TITLE
Step 5, how do I install this, apache config are wrong

### ISSUE THREAD

**Issue by kowo-zahl** [diafygi/gethttpsforfree#46]
There is no domain.crt file or intermediate.pem, because we put the keys in the chained.pem file.

This works fine:

SSLCertificateFile    /etc/ssl/certs/chained.pem
SSLCertificateChainFile /etc/ssl/certs/chained.pem

**Comment by licaon-kter** [comment]
Maybe this explains the chained issue for Apache: https://github.com/diafygi/gethttpsforfree/pull/36

**Comment by diafygi** [comment]
@kowo-zahl the instructions for apache and nginx have been split out, so you no longer create chained.pem in the apache instructions.
