### ISSUE TITLE
Problem with SSLOpenSSLConfCmd

### ISSUE THREAD

**Issue by kowo-zahl** [diafygi/gethttpsforfree#47]
SSLOpenSSLConfCmd DHParameters calls an error on my Apache/2.4.7 .
It could be this:

The set of available SSLOpenSSLConfCmd commands depends on the OpenSSL version being used for mod_ssl (at least version 1.0.2 is required). For a list of supported command names, see the section Supported configuration file commands in the SSL_CONF_cmd(3) manual page for OpenSSL.

https://httpd.apache.org/docs/trunk/mod/mod_ssl.html#page-header

**Comment by licaon-kter** [comment]
Maybe this explains the chained issue for Apache: https://github.com/diafygi/gethttpsforfree/pull/36

**Comment by diafygi** [comment]
Since apparently there's way too many gotchas and version complexities associated with dhparams on apache, I removed SSLOpenSSLConfCmd entirely. It's up to the sysadmin to determine their own dhparams setup.
