### ISSUE TITLE
Checking ownership of domains

### ISSUE THREAD

**Issue by ghost** [diafygi/gethttpsforfree#5]
Hello,
I have a small problem. Let's Encrypt whitelisted me domain and subdomains. But in final, I have like 20 subdomains that I must verify ownership... Is there way to (for example) check only the main domain? (something.com)
Thanks!

**Comment by diafygi** [comment]
Howdy, Let's Encrypt requires you verify ownership of every single domain and subdomain. You can create a single CSR with all of the domains (see "how do I generate this?" in Step 2).

Alternatively, you can use the official [Let's Encrypt client](https://github.com/letsencrypt/letsencrypt) or my [acme-tiny](https://github.com/diafygi/acme-tiny) client to automate the process of issuing the certs.

Hope that helps!
