### ISSUE TITLE
Step #3 failing

### ISSUE THREAD

**Issue by HQuest** [diafygi/gethttpsforfree#51]
Error: Account registration failed. Please start back at Step 1. {"type":"urn:acme:error:malformed","detail":"Unable to read/verify body :: JWS verification error","status":400} 

Tried with Chrome 47/MS Edge on Windows 10 x64. Account key was generated with openssl-1.0.2d-fips-2.0.10 for Windows, CSR is from Cisco IOS.

CSR:
-----BEGIN CERTIFICATE REQUEST-----
MIIDEDCCAfgCAQAwgakxETAPBgNVBAgTCE5lYnJhc2thMQswCQYDVQQGEwJVUzEY
MBYGA1UEChMPQWxleCBIYXV0ZXF1ZXN0MQ8wDQYDVQQLEwZyb3V0ZXIxHTAbBgNV
BAMTFHJvdXRlci5ocXVlc3QucHJvLmJyMT0wGAYJKoZIhvcNAQkIEwsxOTIuMTY4
LjAuMTAhBgkqhkiG9w0BCQIWFHJvdXRlci5ocXVlc3QucHJvLmJyMIIBIjANBgkq
hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxVDvMml9YOTYGRb8emjyD1QC/0iK5MAU
o7NPEpF2219ZmxcPN/ahVW/o4fFj1x1YtMhQlX15QeR3Os3z+qbz16vWV4dPRKT7
JDdWtpTlRc3uFXJRJktCC1J6KGh0GuGEWnjEAfMVu2baDU5wqtqBity83CAEVoU9
+7couSHS94PskafPgo6wuiNbgP+FpL4iaX3YlVVL2bjPZ8DkehrvUFv37LMmkWtV
vFnKK4IhKfmPiZQ5VQnD7r9rLhoxhPWQI3q1eYuLRvSSqdnKvu33vlCOmS7oTTLX
j2McGg7AN/up/0k0x5ClFBWXg39YZ0DfQBtycbuzwz7U14eD4/LEuQIDAQABoCEw
HwYJKoZIhvcNAQkOMRIwEDAOBgNVHQ8BAf8EBAMCBaAwDQYJKoZIhvcNAQELBQAD
ggEBAIePDP+985TxMDkEfvi+QIacnF5rUAtsm7jLgAghEQL2InnTOydjIeWk0tNE
FTeFEEwgjOStkeS1aUS3E0Nhd3N99isaUXEurqsb3vYfBR5ipmYFNvKi9OgUuztG
IOgTWFvApwCWXk2mWYlizOrGi+I06E/rNrChqcQ1kCg+2grrpsfGv4bqYi66Blpt
R4rLD2J+Do13Oxqzq2tevzj4XL/iaOaPFm+aEtH5NgIog6U7JCAUQDKwh+z1QqQ5
lZhYryQRDu4fPxKHL9nBaluIXq2kmiZfC++WykHdj3xeBfLB9qO9g55CTeoYZT0I
hs6WYY9CcExAV9xauBpZlDwLOWc=
-----END CERTIFICATE REQUEST-----

C:\openssl-1.0.2d-fips-2.0.10\bin>echo "eyJub25jZSI6InU1QnlNekg0TDRaNjNadFdvOFhTNHBKV0NhR29BZE5odWJ0djZfb0pHTEEifQ.eyJyZXNvdXJjZSI6Im5ldy1yZWciLCJjb250YWN0IjpbIm1haWx0bzpocXVlc3RAZ21haWwuY29tIl0sImFncmVlbWVudCI6Imh0dHBzOi8vbGV0c2VuY3J5cHQub3JnL2RvY3VtZW50cy9MRS1TQS12MS4wLjEtSnVseS0yNy0yMDE1LnBkZiJ9" | openssl dgst -sha256 -hex -sign privkey.pem
(stdin)= 5a4ee6cde0529ae572b0bbebb907d0b8126ca334ecad2d0c51df088cffaade89eaccc629081b8ca2d94682d60a26c5cabc5b0340fd8c336ae3084414162db19c765f98254a3465542b11952dddb1ccd16ede4121c1b5c47ebaf7acfa89de9a29f4e5734375af6bed1bf36dfe99cee6491edc84c80d319c8b0f2d846dae60fdd243a42aef07193f0f42404a07924c5f4d660aac83537bca7145f7440ca1fb622116a61e5c08bc47ea3f51effa1619ff3e9ab5f9f16db7285ee254bce69b2c00e97bb0eb08f0c959e2983fa62b650f460f9c16ba96a9104de47826f80c4b9057cdf163d8510750e78b811a5878a5a87b6d6ad0746552e4b6ed2a1ed479605404deb2fccb02dfd450b4066f06df45823a4fe8643ca05fb6c9d93ec90b440b3b980400e16cc2cb9e84133f4fd644424209fb9ea51abea04f0d62b656ed90b6bcf11568b543e9dbc9665d49403ef9f158e59c8870be6200c6378f46e2046283deb5fc2fbd701a8a6584b7035a1b30a95d0c65bed95952cda88a8504fc74dece97e9a4785c25e15bf8edff537fd0214a5d4e70f711a007670b3ac21f5c44fe59a737b2a2d156a3402b5d8e404207e5da026766de80c93fe3a3ae33208bc4eb663767428b195c4d7539f7b71a48cd6738861068beedabc598ceebf10580318793c6bed5e782b321563f182680ec445c6b9b0905ae42229d114d32ba0fa9c12c46b78db9

C:\openssl-1.0.2d-fips-2.0.10\bin>echo "eyJub25jZSI6IndxTU41WXIwazdoLWxUemJreUZuVWlfaVJEUkJRT0hOZTB3V29VUVVNdm8ifQ.eyJyZXNvdXJjZSI6Im5ldy1hdXRoeiIsImlkZW50aWZpZXIiOnsidHlwZSI6ImRucyIsInZhbHVlIjoicm91dGVyLmhxdWVzdC5wcm8uYnIifX0" | openssl dgst -sha256 -hex -sign privkey.pem
(stdin)= 0c240bf60f2054079f51b17cfccc5e0276dfd8513f6446a5ea819ba8fbf7678fec48905cab3c86343f9e0f235a588d6a3faa4b3ccb4c0252639eb38c43bca524b87cf963e2e45e71df3a8494e2089be4a73292d6faa2b9b96819c284375c69bef6a6dc88edbacaf720e146b7f0c7a53080acb1f21456fa5d72e73271ad0995af2b4087621ba6bf39e27de7e43a891bd3b8e515ab41de2d9f44a92ff86b64922fbf2ee02304835956fd63789ef9d669b410a46de4fc86b80b69c582e02853f7411e31259ebfb4c0ceafd734a5b5c0ce3bd02b13c780694086760d1280595f11e69b16bba5bff87bf2d964d3610fc86fcf9acf3435ef971275245ecdf9c8ef8c8378b8d6496580542c219d19235044786df9eb608605cc2b1b670d8a5bfdf6222483344ee7a4753c3debb8e1edc751834d52d59f40d221f5219ae38f9962b4c12144288717d671694d575c1c3e56b83ff9742579ccd09e7eb1115c43c8b17cd956dd324758d785ac0e1fe3e1b463a2e80e6e66ccd12e25dcc6f359f3c020debe5c4a691838de8fb177c627e4a233318f6c67c29358a72d2f359986d29e6905fb4e898c3dfdb583c8d5fc7c59e7b777c1e91c82c3a52bf0e18d07aeef6e60c1426c29034a27a27fed6307ea29b0eb8df6cdf2d49a12e521a1fbda0bdfeb91a9f49c0500dadd7af89f77644a4de5f505ee0a749bbb310f90a01052e5c753604bb456

C:\openssl-1.0.2d-fips-2.0.10\bin>echo "eyJub25jZSI6IjFMTXVLcFY5ejBJbEJIb3VGZmZPN2xIcEFGbTJBeHNuN0ZucDBJZW9aaFEifQ.eyJyZXNvdXJjZSI6Im5ldy1jZXJ0IiwiY3NyIjoiTUlJREVEQ0NBZmdDQVFBd2dha3hFVEFQQmdOVkJBZ1RDRTVsWW5KaGMydGhNUXN3Q1FZRFZRUUdFd0pWVXpFWU1CWUdBMVVFQ2hNUFFXeGxlQ0JJWVhWMFpYRjFaWE4wTVE4d0RRWURWUVFMRXdaeWIzVjBaWEl4SFRBYkJnTlZCQU1URkhKdmRYUmxjaTVvY1hWbGMzUXVjSEp2TG1KeU1UMHdHQVlKS29aSWh2Y05BUWtJRXdzeE9USXVNVFk0TGpBdU1UQWhCZ2txaGtpRzl3MEJDUUlXRkhKdmRYUmxjaTVvY1hWbGMzUXVjSEp2TG1KeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeFZEdk1tbDlZT1RZR1JiOGVtanlEMVFDXzBpSzVNQVVvN05QRXBGMjIxOVpteGNQTl9haFZXX280ZkZqMXgxWXRNaFFsWDE1UWVSM09zM3otcWJ6MTZ2V1Y0ZFBSS1Q3SkRkV3RwVGxSYzN1RlhKUkprdENDMUo2S0doMEd1R0VXbmpFQWZNVnUyYmFEVTV3cXRxQml0eTgzQ0FFVm9VOS03Y291U0hTOTRQc2thZlBnbzZ3dWlOYmdQLUZwTDRpYVgzWWxWVkwyYmpQWjhEa2VocnZVRnYzN0xNbWtXdFZ2Rm5LSzRJaEtmbVBpWlE1VlFuRDdyOXJMaG94aFBXUUkzcTFlWXVMUnZTU3Fkbkt2dTMzdmxDT21TN29UVExYajJNY0dnN0FOX3VwXzBrMHg1Q2xGQldYZzM5WVowRGZRQnR5Y2J1end6N1UxNGVENF9MRXVRSURBUUFCb0NFd0h3WUpLb1pJaHZjTkFRa09NUkl3RURBT0JnTlZIUThCQWY4RUJBTUNCYUF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUllUERQLTk4NVR4TURrRWZ2aS1RSWFjbkY1clVBdHNtN2pMZ0FnaEVRTDJJbm5UT3lkakllV2swdE5FRlRlRkVFd2dqT1N0a2VTMWFVUzNFME5oZDNOOTlpc2FVWEV1cnFzYjN2WWZCUjVpcG1ZRk52S2k5T2dVdXp0R0lPZ1RXRnZBcHdDV1hrMm1XWWxpek9yR2ktSTA2RV9yTnJDaHFjUTFrQ2ctMmdycnBzZkd2NGJxWWk2NkJscHRSNHJMRDJKLURvMTNPeHF6cTJ0ZXZ6ajRYTF9pYU9hUEZtLWFFdEg1TmdJb2c2VTdKQ0FVUURLd2gtejFRcVE1bFpoWXJ5UVJEdTRmUHhLSEw5bkJhbHVJWHEya21pWmZDLS1XeWtIZGozeGVCZkxCOXFPOWc1NUNUZW9ZWlQwSWhzNldZWTlDY0V4QVY5eGF1QnBabER3TE9XYyJ9" | openssl dgst -sha256 -hex -sign privkey.pem
(stdin)= 29a6b49a68ea4022b9ae6c5a01f20562091dbdbceca1bbb021c66bcf6289db2492656096c7c68c7cd195061631a375823a8eddf085ded96549b638aaa9c398101dafe8d52b142480f34d5103269af14b1438186de2b770dd029326b17cafd273ed497f00e06607fa1dac4b6de76efc17b325bda7252e00937d2aa243fc737d720444b107d815c8c4d8cb627d99724057cfc8a19540b290d6e82bc58f2d6f3da758f5e1ab7644666daae149adbde2242c1f4e89f9bdcac159bc82eebf001084bfb7e337689491933ef819430ade5cbab05c4def28b7819c3198d2349e5d6f2221ad81683c7914a76bee6c1227d8accf21d1e1223d89f5163c67b73f7e6a2acbb2b4bddb9b3cb4280357c8c19107b2ae10c8058871cd7ba3e3fb6cb05f3531fe03620da2f9bc4403f460ed1591d670d73cf1c16c1f5da2e508206f38ab20c431aed209693f2d082c82f567174645485d824727ba2054ac0d1f8bc9cafde6963e4ae73a9cc92ed7121eccd61c43977e488a4972846172f6cbe3a90310277a12f0767da3f41b726fe4a5c95a7d87636c94a0bbdcff6767ffd9ac8ffb93618596295d5eb9e0968ab4775e340a3cba86758e3ccf90ccea6a5f5bfec2a3b19f2d528f36fd679045ea554cd69ab36b42c75edc021f58e74d037a442ead5f0fa01803ee4eeee171bff05dd1d95d058c551fe01db6e4e60e2a863d0c652dbaf1cebf8a4439

**Comment by HQuest** [comment]
Seems like a bug in OpenSSL for Windows - worked on OpenSSL 1.0.1e-fips on a Linux box.

EDIT: It was actually Windows echo syntax adding an extra break/new line and the quotes.

**Comment by diafygi** [comment]
Does `echo` work on Windows? Also, it may be that echo is adding a line break at the end of the output, which inadvertently gets included in the signature body.

**Comment by HQuest** [comment]
Echo works on Windows, but you are correct: by default, it adds a line break - and it does not require quotes around the digest message, otherwise it outputs the quotes too.

For Windows, the correct command line would be something like

set PRIV_KEY=account.key
echo|set /p=deadbeef... | openssl ... %PRIV_KEY%

Tested and seems to work - got the same hash output as of my Linux box

**Comment by giotec** [comment]
How would you use this correct command line in windows?

**Comment by HQuest** [comment]
@giotec the command syntax is summarized on my post just above your question:

set PRIV_KEY=account.key
echo|set /p=deadbeef... | openssl ... %PRIV_KEY%

All you need to do is replace the missing gaps with the information provided on the GetHTTPSForFree web page at the moment you are creating your certificate -- "deadbeef..." by the long base64 string, "openssl ..." with the OpenSSL parameters for each step of signing and hashing.

Last but not least, you still need to download and install a copy of OpenSSL for Windows.

If you can't figure out what to replace and where to replaced on each step, then - don't get me wrong - I'm afraid you need to follow the official, Linux-based steps on a Linux-based console for further assistance. AFAIK Windows is not officially supported.

**Comment by giotec** [comment]
@HQuest 
What is the purpose of "deadbeef" in the cammand?

I've installed OpenSSL already

**Comment by mavoe01** [comment]
@giotec
For MS-Windows the Command for step 3.1 - 3.3 is:
echo|set /p=ey...iJ9 | openssl dgst -sha256 -hex -sign %PRIV_KEY%
with the ey...iJ9 replaced by the check-string out of the Linux-Command (without quots).

But also with this right commands I finshed Step 3 with:
Error: Account registration failed. Please start back at Step 1. { "type": "urn:acme:error:malformed", "detail": "JWS verification error", "status": 400 }
In the moment I belive, that the reason for that is,;
a) the port-noumber (e.g. 45456) in the domain name for which I requested the certifikat or
b) the password protection of the domain.
I tryed to generate a certificat for my router, which do NOT allow a standard port number nor no Password. The routers is named FRITZ!BOX. It uses a service wich is named "myfritz" to allow the access form the internet with a dynamic IP-Adress.

**Comment by teknoteam** [comment]
On windows it's correct:
set PRIV_KEY=account.key
echo|set /p=deadbeef... | openssl ... %PRIV_KEY%
But remove spaces:
set PRIV_KEY=account.key
echo|set /p=deadbeef..**.|o**penssl ... %PRIV_KEY%

**Comment by goodmuyis** [comment]
In My Case I use Git for window to generate the stuff but was stuck with same problem. So I head to sslforfree.com to save myself from much wahala, Along the line I encounter same error at the last stop. It was then I figured out the am using wildcard which LE does not support yet so I remove the wildcard(ed) domain and it then work (on sslforfree.com actually I trust those guys sha )
