### ISSUE TITLE
Add Support for Step 4 (ACME Challenge) on https / different Ports

### ISSUE THREAD

**Issue by CJHarms** [diafygi/gethttpsforfree#52]
Hi there,

I have a Feature Request and as I'm not really capable to do it myself so I'm hoping someone else can realize it:
## Problem:

In Step 4: ACME Challenge / Authorization the LE API always checks the Webserver (for which you request the Certificate) on Port 80 (http) for the /.well-known/acme-challenge
## New Feature Request

It would be fantastic if there would be some kind of Option (Dropdown Box or a Empty Input Field) to tell the LE API to verify against https or even against a custom Port for the ACME Challenge.
## additional Information

In the official LetsEncrypt Python Client there is a --dvsni-port (now called TLS-SNI-01) which does the trick.

If I can assist with something other than the Coding let me know and I'll try to help. Thanks!

Greetings,
Claus

**Comment by alariel** [comment]
If you direct all traffic from the unencrypted (Port 80) instance to https (via 301 status) it just works, at least for me. Maybe one can add a specific redirect for the checked files/directories...

For Apache, i simply did `Redirect 301 "/" "https://www.domain.de/"` in the `<VirtualHost *:80>`\- part of the config.

A configurable part would be nice to have, though... but i think it's limited to what LE implements/already has implemented...

**Comment by CJHarms** [comment]
I would gladly do that, but due to regulations the Web Servers are only available on 443 and not even listening on Port 80 (not even for redirects to 443).

**Comment by pastly** [comment]
I would really appreciate this too. If I want to verify something to be hosted on my home Internet **from** my home Internet, I need to be able to specify a different port. My ISP blocks incoming port 80 (not 443, interestingly). 

edit: Now that I've said this, I wonder if gethttpsforfree is really the project to be asking for this feature. Since fumbling around last night with this, I bought a cheap VPS and have it temporarily change the DNS record, do webroot auth, then change the DNS record back.

**Comment by diafygi** [comment]
DVSNI would be a big pain to implement in a user-friendly manner to this website, so I don't plan to do it. Would be happy to be impressed by a good pull request, though.

**Comment by Miserlou** [comment]
+1 for this feature, this would be massively useful for using with [django-zappa](https://github.com/Miserlou/django-zappa), as we have no ability to serve over HTTP.

A dropdown with a choice between HTTP and HTTPS would suffice for our purposes, and be MASSIVELY helpful!
