### ISSUE TITLE
Stuck at Step 4

### ISSUE THREAD

**Issue by roshin8** [diafygi/gethttpsforfree#53]
Error: Domain challenge failed. Please start back at Step 1. {"type":"urn:acme:error:malformed","detail":"Unable to read/verify body :: JWS verification error","status":400}
I tried it several times, namelookup for the domain works, I can browse it manually.

**Comment by diafygi** [comment]
Can you please copy and paste the Step 4 signature command and result into this bug? Thanks!

**Comment by varshanbp** [comment]
Check whether your link is visible below. 
https://tools.keycdn.com/curl

Some servers block it for bots.
I have also experienced it several times

**Comment by diafygi** [comment]
Having not heard back in a while. I'm assuming this issue has been resolved on their end.

**Comment by mulle-nat** [comment]
I guess this error occurs, when you take too long to do Step 4. Because I just had this, when going to lunch inbetween

**Comment by marcmanley** [comment]
> Error: Domain challenge failed. Please start back at Step 1. {"type":"urn:acme:error:malformed","detail":"Unable to read/verify body :: JWS verification error","status":400}
> I tried it several times, namelookup for the domain works, I can browse it manually.

I am having the same error. Been trying this all day!
