### ISSUE TITLE
change the name

### ISSUE THREAD

**Issue by treaki** [diafygi/gethttpsforfree#54]
you should not name this "get https for free", cause with tls certificates not only http connections can be encrypted "get tls cert for free" would be in my opinion a better name. Also consider switching from .com to .org for a non commercial project website

**Comment by licaon-kter** [comment]
The title is pure marketing, and a simplification of the whole issue, right what Let's Encrypt wants to be, an easy way to get a certificate.

/mark as wontfix?

**Comment by diafygi** [comment]
You're welcome to buy gettlsforfree.com, and fork the project :) Just be prepared to maintain it ;P
