### ISSUE TITLE
Stuck at step 3

### ISSUE THREAD

**Issue by varshanbp** [diafygi/gethttpsforfree#56]
Stuck at step 3. Not working. Execute and pasted correct output
![image](https://cloud.githubusercontent.com/assets/11254905/12014684/ef99577a-ad56-11e5-9076-063dbc9b7f30.png)

**Comment by diafygi** [comment]
I'm guessing that `echo` added a line break to the end of the string. I'm not sure if the `-n` in the echo command works in Windows. How are you running echo on windows?

**Comment by varshanbp** [comment]
I am running in linux CentOS. What is the solution to this.

**Comment by diafygi** [comment]
Gotcha, can you please try clearing your cache and refreshing the page?

**Comment by diafygi** [comment]
The reason why you're getting this error is that your signatures aren't passing the following regex: `(?:\(stdin\)= |)([a-f0-9]{512,1024})`. Are your signature hex lengths 512 or 1024 characters long?

**Comment by varshanbp** [comment]
My HEX length is 1024 characters long

**Comment by varshanbp** [comment]
Ok, I got it, while copying there was some extra spaces in hex signature

**Comment by xenophonf** [comment]
BTW, if you try this on FreeBSD using tcsh, for some reason the echo commands are getting truncated, which leads to the same error.  Running them under sh works fine, though.
