### ISSUE TITLE
path with "." doesn't work on my system...

### ISSUE THREAD

**Issue by kaffeeringe** [diafygi/gethttpsforfree#57]
I tried the file based authorization but my services provider seems to have restricted paths starting with a dot to just the first level. No files within acme-challenge are found... 

Either drop the dot or make the path configurable...

**Comment by licaon-kter** [comment]
Ask your service provider for help: https://community.letsencrypt.org/search?q=dot

**Comment by diafygi** [comment]
The ACME protocol requires that the challenge file be hosted in the `.well-known/acme-challenge/` directory.

**Comment by kaffeeringe** [comment]
Yes, sorry I just found out. And I also found out that it doesn't work with my provider because they are already preparing for a native Let's Encrypt support! \o/
