### ISSUE TITLE
Step 3: Sign API Requests fails when attempting to register

### ISSUE THREAD

**Issue by tab00** [diafygi/gethttpsforfree#60]
The response from POST request to "https://acme-v01.api.letsencrypt.org/acme/new-reg" is:
{"type":"urn:acme:error:malformed","detail":"Unable to read/verify body :: JWS verification error","status":400}

**Comment by martin-s** [comment]
Kind of same error like in #62.

**Comment by diafygi** [comment]
Likely because you have a newline. Be sure to use `echo -n` or `printf` when piping the signature payload into openssl.

**Comment by TLMcode** [comment]
This issue is closed but not resolved. I've used the exact echo setup and I still get the same error

**Comment by rolexim** [comment]
I've used the echo in a proper way, same error, I'm unable to pass the step 3.
