### ISSUE TITLE
Allow retry on "I'm serving this on <domain>"

### ISSUE THREAD

**Issue by PhilipDeegan** [diafygi/gethttpsforfree#61]
If there is a connection problem at the time of clicking the button, the whole process has to be restarted.

Is there a reason why this is the case?

Thanks for the app!

**Comment by dandee** [comment]
Same here! I've failed on the validation for the last of my subdomains for no apparent reason and needed to repeat the whole process again (and again, and again). It feels like a punishment for trying to be independent... :(

**Comment by iandevlin** [comment]
Running into this now, although I AM serving the file correctly the button fails and now I am stuck.

**Comment by diafygi** [comment]
I wanted to keep the source code less complex, so error handling is super simple (go back to the start).

**Comment by Dekken** [comment]
Thanks for the app, but that's a really awful answer.

I had to restart three times.
