### ISSUE TITLE
Error: Account registration failed API sign

### ISSUE THREAD

**Issue by durcar86** [diafygi/gethttpsforfree#62]
Thank you for the help, im getting stuck on step 3. I appreciate the help

Error: Account registration failed. Please start back at Step 1. {"type":"urn:acme:error:malformed","detail":"JWS verification error","status":400}

My Account Public Key:
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtKSmVLxS8U8zo/bLLBbU
R222pDEKm8aR7pxi/eLzywyPNtA83mke9G+dNgr/3ipOhYoPkcXXEMBviNROJ3y4
kvUShzqIUfoONbTU9Hh3HxiW3GARnWluJDNHiTBVfvWU690f2ieptg4V401Xjudb
UZ4KH5z1AZxGB46O18X2H2PtmXFpt8C065CnScyMf0bnI1zwxg79D0SrF7Nt7Cfi
VJON4FfpqEGqYHen6mYRFKRtuJ2HrTWd/IPf/xR8xDRoCgA+tZHh+/MkEPij6++A
JZzSSQk8eKmJE3Jelct2hZS8VKuQrPYnhRymh1FuPBLnBnHmOYT9KgN//Oj5eG4O
YwIDAQAB
-----END PUBLIC KEY-----

CSR:
-----BEGIN CERTIFICATE REQUEST-----
MIICgTCCAWkCAQAwADCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAO0b
3G3Rc/EzxacMMq4XZ7ntFwf2DC+xVgtmeCQyHJMal/pcK4phfsUwMeJakEqu/Gji
QRqeiSrMZXVC1AaEsj3xt6QTZ/asbrZ3Nc2xOG5biXu5fVMFIyguPrZmWTkJ94kB
ABo+nQHa0pGlJynb0weirYaCidw5rTfAaTdx9s/7HMM5rEEF/gtA6sJ70WTHvESt
6ZC4K2ak3KecHx68PV6f1gioLWJ/Oot8AwxIWuSvBiNZ8mrb7loh/kxxqvC0U1hh
s/jXgMpbF6BwaeBW5KVhlFTnswak0L2m38hT+qtj6CE4PscTIGZHcT+ucoeWPpW8
XzGRxIhy4JZxUWm5HxcCAwEAAaA8MDoGCSqGSIb3DQEJDjEtMCswKQYDVR0RBCIw
IIIMY2FybGR1cnIuY29tghB3d3cuY2FybGR1cnIuY29tMA0GCSqGSIb3DQEBCwUA
A4IBAQB5w6lJ0DkkubdpjUMCk4FVwIvRjtQALQcXuk7Ha79hrVg93QgR3ZfUisJW
uFI0p5KNUUvQNBMIhGyZyIC/PF9fOr+DHg3NOj9mXzzZyX3Xc1IpQF07B8eyFh1V
kkLx2sR40Ut6uwwKpTRaI3ExltI9yVzW6G/7fuTXtQtCk1i5CFPh8rSv2gPtFfde
lUNNz7KX+BNXB0yURr2FMMOoBbzw/g3lmZ+MYClbb1zXZ7ikd2Kxz51s/BlLZojT
Mt2VaMyvs2kMOZV0Sx++8/2kr+25DruCDnL6ObpG4q0JBEUjL6fyW4TZ3hUHPHv5
ZDvfG8UDgeHYlpga0YjRG4eboNau
-----END CERTIFICATE REQUEST-----

API:

PRIV_KEY=./account.key; echo -n "eyJub25jZSI6Im5LQ2czdFNic05DNWU0R3ZZb1BPZG96OGtHb3dqVkRyZndJMUI3Yl9tVmMifQ.eyJyZXNvdXJjZSI6Im5ldy1yZWciLCJjb250YWN0IjpbIm1haWx0bzpjYXJsZHVyckBjYXJsZHVyci5jb20iXSwiYWdyZWVtZW50IjoiaHR0cHM6Ly9sZXRzZW5jcnlwdC5vcmcvZG9jdW1lbnRzL0xFLVNBLXYxLjAuMS1KdWx5LTI3LTIwMTUucGRmIn0" | openssl dgst -sha256 -hex -sign $PRIV_KEY

PRIV_KEY=./account.key; echo -n "eyJub25jZSI6IkpwVWFOZ2t5ZXY0VHhPYTdjd2FkS1ZISnBaLXZQWmxHMUI2VXAzMEs5WjQifQ.eyJyZXNvdXJjZSI6Im5ldy1hdXRoeiIsImlkZW50aWZpZXIiOnsidHlwZSI6ImRucyIsInZhbHVlIjoiY2FybGR1cnIuY29tIn19" | openssl dgst -sha256 -hex -sign $PRIV_KEY

PRIV_KEY=./account.key; echo -n "eyJub25jZSI6ImV5MmNRMWEwMk12S3FHQjlEN3VGaXdkM2RkMlZPRjZac2RheV9LSWtKWDQifQ.eyJyZXNvdXJjZSI6Im5ldy1hdXRoeiIsImlkZW50aWZpZXIiOnsidHlwZSI6ImRucyIsInZhbHVlIjoid3d3LmNhcmxkdXJyLmNvbSJ9fQ" | openssl dgst -sha256 -hex -sign $PRIV_KEY

PRIV_KEY=./account.key; echo -n "eyJub25jZSI6InBDTGlGbHVIWUJ6N0VvVVotcXlqZnRBVjJfQ0dGVXFGOGpXT2FYYnhOTE0ifQ.eyJyZXNvdXJjZSI6Im5ldy1jZXJ0IiwiY3NyIjoiTUlJQ2dUQ0NBV2tDQVFBd0FEQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU8wYjNHM1JjX0V6eGFjTU1xNFhaN250RndmMkRDLXhWZ3RtZUNReUhKTWFsX3BjSzRwaGZzVXdNZUpha0VxdV9HamlRUnFlaVNyTVpYVkMxQWFFc2ozeHQ2UVRaX2FzYnJaM05jMnhPRzViaVh1NWZWTUZJeWd1UHJabVdUa0o5NGtCQUJvLW5RSGEwcEdsSnluYjB3ZWlyWWFDaWR3NXJUZkFhVGR4OXNfN0hNTTVyRUVGX2d0QTZzSjcwV1RIdkVTdDZaQzRLMmFrM0tlY0h4NjhQVjZmMWdpb0xXSl9Pb3Q4QXd4SVd1U3ZCaU5aOG1yYjdsb2hfa3h4cXZDMFUxaGhzX2pYZ01wYkY2QndhZUJXNUtWaGxGVG5zd2FrMEwybTM4aFQtcXRqNkNFNFBzY1RJR1pIY1QtdWNvZVdQcFc4WHpHUnhJaHk0Slp4VVdtNUh4Y0NBd0VBQWFBOE1Eb0dDU3FHU0liM0RRRUpEakV0TUNzd0tRWURWUjBSQkNJd0lJSU1ZMkZ5YkdSMWNuSXVZMjl0Z2hCM2QzY3VZMkZ5YkdSMWNuSXVZMjl0TUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCNXc2bEowRGtrdWJkcGpVTUNrNEZWd0l2Ump0UUFMUWNYdWs3SGE3OWhyVmc5M1FnUjNaZlVpc0pXdUZJMHA1S05VVXZRTkJNSWhHeVp5SUNfUEY5Zk9yLURIZzNOT2o5bVh6elp5WDNYYzFJcFFGMDdCOGV5RmgxVmtrTHgyc1I0MFV0NnV3d0twVFJhSTNFeGx0STl5VnpXNkdfN2Z1VFh0UXRDazFpNUNGUGg4clN2MmdQdEZmZGVsVU5OejdLWC1CTlhCMHlVUnIyRk1NT29CYnp3X2czbG1aLU1ZQ2xiYjF6WFo3aWtkMkt4ejUxc19CbExab2pUTXQyVmFNeXZzMmtNT1pWMFN4LS04XzJrci0yNURydUNEbkw2T2JwRzRxMEpCRVVqTDZmeVc0VFozaFVIUEh2NVpEdmZHOFVEZ2VIWWxwZ2EwWWpSRzRlYm9OYXUifQ" | openssl dgst -sha256 -hex -sign $PRIV_KEY

**Comment by huanjue** [comment]
Me too.

**Comment by konstantinpae** [comment]
same here

**Comment by martin-s** [comment]
Same error 400 here. Tried with hex codes in format
`"(stdin)= f2c..."` and `(stdin)= f2c...`

Actions are:

```
set PRIV_KEY=account.key
echo "ey..." | openssl dgst -sha256 -hex -sign %PRIV_KEY%>out.sign
```

The signature in out.sign contains the hex code which I enter in step 3.The key is the private key of my account. The standard input (in echo command) is taken from website in step3.
The environment is windows 7, OpenSSL 1.0.2f.
Post request includes JWK token, payload, protected and signature elements. Any hints on this?

**Comment by yamanoor** [comment]
Just adding my voice. Tried to get the entire code in one line, etc, but still fails every time in Windows 7.

**Comment by durcar86** [comment]
I ended up using https://www.startssl.com/Account to validate my crt file. The Website is a little slow, but in the end i was able to get it working. Best of Luck

**Comment by martin-s** [comment]
I compared it to a bash console and looked what's going on. Following solution is available for Windows console (e.g. batch script):

```
set PRIV_KEY=account.key
(echo | set /p dummyName="ey...") | openssl dgst -sha256 -hex -sign %PRIV_KEY% -out out.sign
```

Problem is the bash **echo -n** (echo without newline) which has to simulated in Windows environment. The Windows solution **echo | set /p dummyName="ey..."** will print the string without any newline or space character at the end and additionally not raise any errorlevel.

The resulting hex code in file _out.sign_ can be used for step 3 and works.

**Comment by chisleu** [comment]
Mac OSX here w/ ubuntu in the back. Same problem.

**Comment by diafygi** [comment]
Like @martin-s said, this error is likely because your `echo` is adding a newline in the signature. Be sure to either use `echo -n` or `printf` when piping the body into openssl.

**Comment by AlpacaNox** [comment]
@marti-s Thank you so much!
