### ISSUE TITLE
Auto-selecting readonly fields?.. or as-is?

### ISSUE THREAD

**Issue by TheSpiciestDev** [diafygi/gethttpsforfree#68]
This will auto-select the contents of fields the user is supposed to copy from (if the browser is in-compatible then this should still gracefully pass.) Is this PR worthy or will everything be left as-is and nothing more?

``` javascript
function focusOnReadonlyFields(e){
    // IF it's readonly AND a selectable.
    if(e.target.hasAttribute("readonly") && typeof e.target.select === "function"){

        // IF it's what we intend.
        if(e.target.tagName === "TEXTAREA" || (
            e.target.tagName === "INPUT" &&
            e.target.getAttribute("type") === "text"
        )){
            e.target.select();
        }
    }
}
document.getElementById("body").addEventListener("click", focusOnReadonlyFields);
```

(Just certified my first Let's Encrypt site with the help of `gethttpsforfree`, awesome work!)

**Comment by diafygi** [comment]
Eh, not wild about messing with selection mechanics. I usually find it annoying when another website doesn't let me select stuff as I please.
