### ISSUE TITLE
Instructions don't work for OSX (El Capitan)

### ISSUE THREAD

**Issue by OmgImAlexis** [diafygi/gethttpsforfree#7]
```
openssl req -new -sha256 -key domain.key -subj "/" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf "[SAN]\nsubjectAltName=DNS:foo.com,DNS:www.foo.com"))
```

```
cat: /etc/ssl/openssl.cnf: No such file or directory
unable to find 'distinguished_name' in config
problems making Certificate Request
4769:error:0E06D06C:configuration file routines:NCONF_get_string:no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59/src/crypto/conf/conf_lib.c:329:group=req name=distinguished_name
```

**Comment by OmgImAlexis** [comment]
This may be related: https://github.com/phusion/passenger/issues/1630

**Comment by OmgImAlexis** [comment]
Changing the location of the openssl.cnf from `/etc/ssl/openssl.cnf` to `/System/Library/OpenSSL/openssl.cnf` seems to work fine.

**Comment by OmgImAlexis** [comment]
OSX's base64 install doesn't support the `-w` option so it needs to be removed for the commands to work.

**Comment by diafygi** [comment]
Thanks! Instead of giving mac/linux specific commands, I removed base64 entirely from the computer requirements and started parsing hex dumped directly from openssl.
