### ISSUE TITLE
How to perform the last step (Ubuntu 14.04 x86_64 on VPS with Nginx and Vesta)?

### ISSUE THREAD

**Issue by 333van** [diafygi/gethttpsforfree#72]
Hi guys, I have a extremely stupid question to ask. 

I am stuck at step 5.5, which is telling me to:
"
5. Update your webserver config to use https (examples below).
server {
    listen 443;
    server_name foo.com;
    ssl on;
    ssl_certificate /etc/ssl/certs/chained.pem;
    ssl_certificate_key /etc/ssl/private/domain.key;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA;
    ssl_session_cache shared:SSL:50m;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    ssl_prefer_server_ciphers on;

```
location / {
    return 200 'Hello world!';
    add_header Content-Type text/plain;
}
```

}
"
I think I know how to change the template to my need (simply change foo.com to my domain name and which I have tried), but I don't know where the "webserver config" file is. I thought it was "/etc/nginx/nginx.conf", but I couldn't work it out by myself. 

So, how do I perform the last step? I am with Ubuntu 14.04 x86_64 on VPS with Nginx and Vesta on my VPS. The Nginx should probably installed by Vesta automatically. 

Any help will be appreciated. Thx!

**Comment by radnor** [comment]
nginx's configuration file may be inside the `sites-available` subdirectory: `/etc/nginx/sites-available/default`

**Comment by 333van** [comment]
I have checked that directory. I didn't have a folder named "sites-available". That may have something to do with my nginx being set up by Vesta (https://vestacp.com/). I have the content of the folder like this:
root@www:~# cd /etc/nginx/sites-available/default
-bash: cd: /etc/nginx/sites-available/default: No such file or directory
root@www:~# cd /etc/nginx
root@www:/etc/nginx# ls -al
total 56
drwxr-xr-x   3 root root  4096 Feb  1 13:37 .
drwxr-xr-x 120 root root 12288 Feb  1 01:33 ..
drwxr-xr-x   2 root root  4096 Feb  1 13:12 conf.d
-rw-r--r--   1 root root   964 Apr 21  2015 fastcgi_params
-rw-r--r--   1 root root  2837 Apr 21  2015 koi-utf
-rw-r--r--   1 root root  2223 Apr 21  2015 koi-win
-rw-r--r--   1 root root  3957 Apr 21  2015 mime.types
-rw-r--r--   1 root root  4313 Feb  1 13:03 nginx.conf
-rw-r--r--   1 root root   596 Apr 21  2015 scgi_params
-rw-r--r--   1 root root   623 Apr 21  2015 uwsgi_params
-rw-r--r--   1 root root  3610 Apr 21  2015 win-utf
root@www:/etc/nginx# cd conf.d
root@www:/etc/nginx/conf.d# ls -al
total 32
drwxr-xr-x 2 root root 4096 Feb  1 13:12 .
drwxr-xr-x 3 root root 4096 Feb  1 13:37 ..
-rw-r--r-- 1 root root  194 Jan  4 21:23 45.78.46.77.conf
-rw-r--r-- 1 root root  369 Jul 21  2015 phpmyadmin.inc
-rw-r--r-- 1 root root  306 Jul 21  2015 phppgadmin.inc
-rw-r--r-- 1 root root  178 Sep 23  2012 status.conf
-rw-r--r-- 1 root root   42 Jan  4 21:23 vesta.conf
-rw-r--r-- 1 root root  358 Jul 21  2015 webmail.inc

**Comment by TheSpiciestDev** [comment]
Create a `.conf` file in your `/etc/nginx/conf.d` directory. It can be named whatever, so long as it is a `.conf` extension (like your `vesta.conf` file there), as it will then be loaded automatically when NGINX starts. Your `Step 5` configurations will go into that new file and then restart NGINX when you're done, it you have any errors, you should be able to find them logged under `/var/log/nginx/error.log`.

**Comment by 333van** [comment]
Thanks for the light, but I still have an error as below:

root@www:~# cd /etc/nginx/conf.d
root@www:/etc/nginx/conf.d# touch ssl.conf
root@www:/etc/nginx/conf.d# vi ssl.conf
root@www:/etc/nginx/conf.d# sudo service nginx stop
root@www:/etc/nginx/conf.d# sudo service nginx start
nginx: [emerg] unknown directive "Server" in /etc/nginx/conf.d/ssl.conf:1

The error log is telling me the same thing as above ([emerg] unknown directive "Server" in /etc/nginx/conf.d/ssl.conf:1).

Any advice? Thx. 

FYI, the content of the file "ssl.conf" goes:
"
Server {
    listen 443;
    server_name mydomain.com;
    ssl on;
    ssl_certificate /etc/ssl/certs/chained.pem;
    ssl_certificate_key /etc/ssl/private/domain.key;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA;
    ssl_session_cache shared:SSL:50m;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    ssl_prefer_server_ciphers on;

```
location / {
    return 200 'Hello world!';
    add_header Content-Type text/plain;
}
```

}
"

**Comment by 333van** [comment]
Sorry, silly me. I know I have a typo (Capitalized "Server" at the first line). I have fixed that, but I still have an error saying: 
root@www:/etc/nginx/conf.d# sudo service nginx start
nginx: [emerg] the size 52428800 of shared memory zone "SSL" conflicts with already declared size 10485760 in /etc/nginx/conf.d/ssl.conf:10

**Comment by TheSpiciestDev** [comment]
Does [this issue](https://github.com/letsencrypt/letsencrypt/issues/921) provide any additional direction for you? It looks as if there may be two declarations of `ssl_session_cache`... maybe one with `10m`, something that looks like so `ssl_session_cache shared:SSL:10m;`?

**Comment by 333van** [comment]
It works! After I delete the configuration on ssl_session_cache from ssl.conf (I created it with advice from @METACEO. Thx man!), the nginx service can start as normal, and my blog is back online. However, I can conly access my blog with http. If I switch it to https, only hello world is available. I think the problem lies in the last line of ssl.conf (location {}). Is it that I need to direct it to my blog, and if yes, how may I do it?

**Comment by TheSpiciestDev** [comment]
You have a `server` block somewhere listening on port 80 who's `location` block is pointing to your blog, what you want _instead_ is for that `server` block to redirect requests to another `server` block listening on port 443 (for **HTTPS**) who's `location` block points to your blog. You'll have two `server` blocks set up when this is working (these can be in the same `.conf` file.)

```
server {
    listen 80;
    server_name mydomain.com;

    // cut out your blog's location block

    return 301 https://$host$request_uri;
}

server {
    listen 443;
    server_name mydomain.com;

    // your working ssl configurations here

    // paste your blog's location block here
}
```

If your blog's `location` block is causing issues in the port 443 `server` block, hit me back up.

**Comment by 333van** [comment]
I am sorry. I am very new to VPS, ngnix, and WordPress etc. I wasn't quite sure about how to get my "blog's location block". Could you tell me more about that? An example would be appreciated. 

FYI, my WordPress site's config file locates at "/home/admin/web/www.mydomain.com/public_html/wp-config.php".

**Comment by TheSpiciestDev** [comment]
You have a `.conf` file somewhere in your `/etc/nginx` directory that directs requests to PHP and your `/home/admin/web/www.mydomain.com/public_html` directory. While I don't know your setup, I know this `.conf` file exists somewhere and in it are entries you want to keep and put to different use.
If you run this below (the command is broken down [here](https://stackoverflow.com/questions/16956810/finding-all-files-containing-a-text-string-on-linux)...)

```
grep --include=\*.conf -rnw '/etc/nginx/' -e "/home/admin/web/www.mydomain.com"
```

...then the `.conf` file that we're looking for should be listed with the line number of the `location` block that's currently handling requests. In that `.conf` file you will find the `location` block I'm [referring to](#issuecomment-178629599).

**Comment by dylanvalade** [comment]
@iamevanhe instead of stopping Nginx you can run "service ngnix configtest" and see if there are errors with your conf files before potentially taking your server down. If configtest passes with no errors you can run "service nginx reload" to reboot the server with the conf changes without stopping the server.

**Comment by 333van** [comment]
Sorry, I couldn't figure this out. I think I will give up on this. Your eagers to help are deeply appreciated. :)
