### ISSUE TITLE
wildcard certificate for domain

### ISSUE THREAD

**Issue by biswajitpain** [diafygi/gethttpsforfree#73]
How can i generate wildcard certificate for my domain like *.abcd.om

**Comment by ThomasLomas** [comment]
As it stands you cannot do this through Lets Encrypt.

**Comment by TheSpiciestDev** [comment]
@bpain2010 see [Let's Encrypt's FAQs](https://community.letsencrypt.org/t/frequently-asked-questions-faq/26):

> **Will Let’s Encrypt issue wildcard certificates?**
> We currently have no plans to do so, but it is a possibility in the future. Hopefully wildcards aren’t necessary for the vast majority of our potential subscribers because it should be easy to get and manage certificates for all subdomains.

While it stands as a _maybe_, I too share your interest. It's a whole different solution to have a single wildcard cert instead of a cert for each and every subdomain.

**Comment by diafygi** [comment]
Sorry, Let's Encrypt does not issue wildcard certs.
