### ISSUE TITLE
renew certificates

### ISSUE THREAD

**Issue by c64bob** [diafygi/gethttpsforfree#76]
Now that my certificates are about to expire, any chance of getting an option to renew those using the web client? 

Great work by the way!

**Comment by diafygi** [comment]
Renewal is currently exactly the same. Just follow the directions again (using the same account public key and CSR).

**Comment by linus-amg** [comment]
for renewing, i've created an api-mapping in the custom domain, with the base path of .well-known and created a route /acme-challenge/{challenge} + handler which returns the desired string, for everyone who maybe stumbles upon this :p

**Comment by Sebaortiz** [comment]
I'm following the steps to renew, But in step two, when adding the same certificate CSR return an error "Error: Your CSR isn't formatted correctly."
