### ISSUE TITLE
Put CSS into a single file and beautify it

### ISSUE THREAD

**Issue by rugk** [diafygi/gethttpsforfree#83]
Especially for [CPS compatibility](https://github.com/diafygi/gethttpsforfree/issues/80) it is good to not use inline-css.

Additionally the CSS could be formatted a bit more as it currently looks pretty ugly. [csslint](https://github.com/CSSLint/csslint) does a pretty good job in recommending a good style.
This would also make the source much more readable.

**Comment by diafygi** [comment]
Maybe, will think on this and look into CSP options.

**Comment by diafygi** [comment]
Closing since this will likely be done when #80 is fixed.
