### ISSUE TITLE
Step 4: Verify Ownership (Error: Something went wrong. Please go back to Step 1)

### ISSUE THREAD

**Issue by RYAN-JIM** [diafygi/gethttpsforfree#86]
Step 1: Account Info to Step 3: Sign API Requests is complete
but Step 4: Verify Ownership tell me 'Error: Something went wrong. Please go back to Step 1'
what' s the meaning? i using apache!

**Comment by daxpedda** [comment]
Same problem here. Tried it more then 10 times now, gives me always this error:
`Error: Domain challenge failed. Please start back at Step 1. {"type":"http-01","status":"invalid","error":{"type":"urn:acme:error:unauthorized","detail":"Error parsing key authorization file: Invalid key authorization: 19 parts"}`

**Comment by ghost** [comment]
Check that you can access the test file from your browser

**Comment by daxpedda** [comment]
I could. Also checked if its "text/plain".

**Comment by ghost** [comment]
I tried with a brand new domain and I got the same error on step 4

**Comment by RYAN-JIM** [comment]
it's seem have a bug for apache mod

**Comment by bofeng** [comment]
Got the same error too ...

**Comment by diafygi** [comment]
In the `(how do I do this?)` help section for `Option 2 - file based`, it says

"5. Open the link in a new window to make sure it's working: http://<domain>/.well-known/acme-challenge/9dfru893j..."

Be sure to make sure you can download that file. This helps you troubleshoot any webserver config issues before clicking "I am now serving this file on <domain>" button.

**Comment by walidfaied** [comment]
Got the same error too ...
