### ISSUE TITLE
Domain Challenge Failed - urn:acme:error:badNonce

### ISSUE THREAD

**Issue by geirman** [diafygi/gethttpsforfree#87]
I'm getting the following error when attempting to verify ownership of the domain...

> Error: Domain challenge failed. Please start back at Step 1. {"type":"urn:acme:error:badNonce","detail":"JWS has invalid anti-replay nonce 8F21gQC1Ci_CHa9smrPKGVgulnIaWVsDrwZKIAsJFL4","status":400}

I found this open issue which seems to be related...
https://github.com/letsencrypt/letsencrypt/issues/2244

And [this comment](https://github.com/letsencrypt/letsencrypt/issues/2244#issuecomment-174260638) seems to offer a solution

> Ok here is out this finally worked for me, We have to repeat the new certificate step and use the nonce that is sent back with "jws invalid nonce" to get the certificate issued. 
> Otherwise if we go through the whole process again it always fails.

However, I'm not sure how to "repeat the new certificate step and use the nonce that is sent back". 

How do I retry using the jws nonce?

**Comment by diafygi** [comment]
You can always refresh the page and start over if you run into a race condition error like this one.
