### ISSUE TITLE
[error] Sign API Requests not passed to 4

### ISSUE THREAD

**Issue by alexonbalangue** [diafygi/gethttpsforfree#88]
I testing on windows i did all similare on linux but not work,
![capture-test-localhost-letsencrypt](https://cloud.githubusercontent.com/assets/6099946/13905310/93633938-eebc-11e5-823a-804b98d366eb.PNG)

**Comment by Matroschker** [comment]
I got the same error. Using Windows 2008 Server and Apache.
What to do?

**Comment by diafygi** [comment]
I don't think echo's `-n` option is supported on windows. See Step 3 here: https://blog.sverrirs.com/2016/01/installing-free-ssl-certificate-on-your.html

---

You will be issued a series of keys in this step. They will look something like this

```
PRIV_KEY=./account.key; echo -n "eyJ..SNIP..In0" | openssl dgst -sha256 -hex -sign $PRIV_KEY
```

You need to modify them to look like this

```
echo|set /p="eyJ..SNIP..In0" | openssl dgst -sha256 -hex -sign account.key
```

---

**Comment by diafygi** [comment]
Also, it doesn't look like you're copying in the whole response. `(stdin) = ...` should be a lot longer than your screenshot.

**Comment by Matroschker** [comment]
I will check the modified command, I used the command in this way:
echo -n "eyJ..SNIP..In0" | openssl dgst -sha256 -hex -sign account.key
I start the echo command from the directory where the account.key exists. I got a very long HEX string which I pasted in the field under every command.

**Comment by Matroschker** [comment]
Now I checked the modified command, but I got the same error
![19-04-_2016_14-43-25](https://cloud.githubusercontent.com/assets/17358672/14639446/2104b1c6-063d-11e6-904e-f5dd569c320d.png)

**Comment by diafygi** [comment]
You have spaces in the hex towards in the end of the screenshot.

**Comment by Matroschker** [comment]
Thank you very much, the spaces were the problem, it is a copy paste error ;-( 
But now I got this error: Error: Account registration failed. Please start back at Step 1. {"type":"urn:acme:error:malformed","detail":"JWS verification error","status":400}

**Comment by Matroschker** [comment]
The error, I could solve with this --> https://github.com/diafygi/gethttpsforfree/issues/12. In my opinion the cause was the caching from the browser.  At the end I could get a certifcate if using Firefox. Thanks all for the help.
