### ISSUE TITLE
Not able to get CSR 

### ISSUE THREAD

**Issue by shallad** [diafygi/gethttpsforfree#97]
I am trying to run the following command in terminal but always getting syntax error near unexpected token `('.

openssl req -new -sha256 -key domain.key -subj "/" -requexts SAN -config < (cat /System/Library/OpenSSL/openssl.cnf < (printf "[SAN] subjectAltName=DNS:foo.com,DNS:www.foo.com"))

**Comment by licaon-kter** [comment]
What OS?

**Comment by shallad** [comment]
OSX 10.11.4

**Comment by licaon-kter** [comment]
What shell exactly? Bash? Other?

**Comment by shallad** [comment]
I did an echo $SHELL and my output was /bin/sh

**Comment by diafygi** [comment]
Your shell likely doesn't support subshells (what the parentheses are). No worries, you can generate a CSR many other ways: https://easyengine.io/wordpress-nginx/tutorials/ssl/multidomain-ssl-subject-alternative-names/
