### ISSUE TITLE
Shortest domain error

### ISSUE THREAD

**Issue by rapsys** [diafygi/gethttpsforfree#99]
There seems a bug in js code, shortest_domain finish with largest one.

You would need to change sign line 322 of index.js to fix it.
if(shortest_domain.length < domains[d].length){
Should become :
if(shortest_domain.length > domains[d].length){

**Comment by diafygi** [comment]
fixed in https://github.com/diafygi/gethttpsforfree/commit/d000460851965ee2cff8481927758812132d9cad
